// 全球名花数据库 - 120 种名花
const FLOWERS_DATA = [
  // ========== 亚洲 ==========
  {
    id: "orchid_china",
    name: "兰花",
    nameEn: "Orchid",
    country: "中国",
    region: "亚洲",
    location: { lat: 28.2363, lng: 112.9388 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["白色", "紫色", "淡绿色"],
    emoji: "🪻",
    colorHex: "#B39DDB",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Plant_Orchid_Cymbidium_aloifolium_P1110661_05_-_cropped.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/兰属",
    brief: "兰花是中国十大名花之一，被誉为花中君子。品种众多，春兰、蕙兰、建兰最为著名。",
    bloomGuide: "不同种类兰花花期不同，春兰在1-3月开放，香味最为浓郁，花朵精致优雅。",
    viewingTips: "四川、浙江、福建等地均有兰花栽培基地，各地兰花展是欣赏名品的好机会。",
    category: "草本花卉"
  },
  {
    id: "cherry_blossom",
    name: "樱花",
    nameEn: "Cherry Blossom",
    country: "日本",
    region: "亚洲",
    location: { lat: 35.6762, lng: 139.6503 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["粉色", "白色"],
    emoji: "🌸",
    colorHex: "#FFB7C5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/2020-04-07_Prunus_×_yedoensis_Tambasasayama,Hyogo(丹波篠山市篠山川のソメイヨシノ)DSCF2986☆彡.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/樱花",
    brief: "樱花是日本的国花，象征着生命的短暂与美丽。每年春天樱花盛开时，日本各地会举办赏花活动，人们在樱花树下野餐、欢聚。",
    bloomGuide: "最佳观赏期通常在3月底至4月中旬，花期仅约两周。花朵盛开时满树浅粉，落花时如粉色雪花飘落。",
    viewingTips: "推荐前往上野公园、新宿御苑、目黑川等著名赏樱地点。建议提前查阅樱花预报，选择盛开期前往。",
    category: "木本花卉"
  },
  {
    id: "lotus",
    name: "荷花",
    nameEn: "Lotus",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.5928, lng: 114.3055 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["粉色", "白色", "红色"],
    emoji: "🪷",
    colorHex: "#FF8FAB",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Sacred_lotus_Nelumbo_nucifera.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/荷花",
    brief: "荷花是中国十大名花之一，被誉为出淤泥而不染的君子之花。荷花不仅美丽，还是佛教的圣洁象征。",
    bloomGuide: "荷花在夏季盛开，清晨花朵绽放最为美丽，傍晚慢慢闭合。荷叶碧绿如盖，莲蓬清香四溢。",
    viewingTips: "杭州西湖、武汉东湖、济南大明湖等地是观赏荷花的绝佳地点。清晨6-9点是最佳观赏时间。",
    category: "水生花卉"
  },
  {
    id: "peony",
    name: "牡丹",
    nameEn: "Peony",
    country: "中国",
    region: "亚洲",
    location: { lat: 34.6836, lng: 112.4535 },
    bloomSeason: "4月-5月",
    bloomMonths: [4, 5],
    flowerColors: ["红色", "粉色", "紫色", "白色", "黄色"],
    emoji: "🏵️",
    colorHex: "#C03C3C",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Paeonia_suffruticosa01_2048.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/牡丹",
    brief: "牡丹被誉为花中之王，是中国国花候选之一。洛阳牡丹甲天下，每年春天牡丹盛开，艳压群芳。",
    bloomGuide: "花期在4月中旬至5月上旬，约20天。花朵硕大，色彩丰富，香气袭人，一株可开数十朵大花。",
    viewingTips: "河南洛阳是赏牡丹最佳地，每年4月举办国际牡丹文化节。国花园、王城公园都是必游之地。",
    category: "木本花卉"
  },
  {
    id: "plum_blossom",
    name: "梅花",
    nameEn: "Plum Blossom",
    country: "中国",
    region: "亚洲",
    location: { lat: 32.0603, lng: 118.7969 },
    bloomSeason: "12月-3月",
    bloomMonths: [12, 1, 2, 3],
    flowerColors: ["白色", "粉色", "红色"],
    emoji: "❄️",
    colorHex: "#F7B2BD",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Pink_Prunus_mume_flowers.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/梅",
    brief: "梅花是中国国花，象征着坚韧不拔的品格。在严冬中傲雪绽放，与松、竹并称岁寒三友。",
    bloomGuide: "梅花在冬末春初开放，耐寒，在零下数度的低温中仍能盛开，清香远溢，幽雅宜人。",
    viewingTips: "南京梅花山是全国最大的梅花观赏地，武汉东湖磨山梅园、无锡梅园也是著名赏梅地。",
    category: "木本花卉"
  },
  {
    id: "chrysanthemum",
    name: "菊花",
    nameEn: "Chrysanthemum",
    country: "中国",
    region: "亚洲",
    location: { lat: 36.0671, lng: 103.8343 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["黄色", "白色", "红色", "紫色"],
    emoji: "🌼",
    colorHex: "#FFD700",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cúc_mâm_xôi_-_bích_phương_đào.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/菊花",
    brief: "菊花是中国十大名花之一，历史悠久。菊花象征高洁、坚贞，深受文人墨客喜爱。",
    bloomGuide: "菊花在秋季盛开，品种繁多，形态各异。有万头菊、悬崖菊、大立菊等多种造型。",
    viewingTips: "北京植物园、开封菊花文化节、杭州满觉陇都是著名赏菊地点。",
    category: "草本花卉"
  },
  {
    id: "wisteria",
    name: "紫藤",
    nameEn: "Wisteria",
    country: "日本",
    region: "亚洲",
    location: { lat: 36.2048, lng: 138.2529 },
    bloomSeason: "4月-5月",
    bloomMonths: [4, 5],
    flowerColors: ["紫色", "白色", "粉色"],
    emoji: "☂️",
    colorHex: "#9C27B0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Chinese_Wisteria_Blütentrauben.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/紫藤",
    brief: "紫藤是日本春日花卉之一，垂挂的紫色花串如梦如幻，营造诗意景致。",
    bloomGuide: "花期在4-5月，花期约2-3周。花串向下垂挂，香气扑鼻。",
    viewingTips: "日本足利花卉公园拥有世界最大的紫藤树，河内藤园的紫藤隧道也是网红地点。",
    category: "木质藤本"
  },
  {
    id: "bougainvillea",
    name: "三角梅",
    nameEn: "Bougainvillea",
    country: "泰国",
    region: "亚洲",
    location: { lat: 13.7563, lng: 100.5018 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["紫色", "红色", "粉色", "橙色", "白色"],
    emoji: "🌺",
    colorHex: "#E040FB",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bougainvillea_closeup.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/叶子花属",
    brief: "三角梅原产于南美洲，在热带和亚热带地区广泛栽培。花朵颜色鲜艳，常见于东南亚街道。",
    bloomGuide: "在热带地区几乎全年开花。鲜艳的花瓣是苞片，真正的花朵很小。",
    viewingTips: "泰国清迈、曼谷各处街道均可见到大面积盛开的三角梅。",
    category: "木质藤本"
  },
  {
    id: "hibiscus",
    name: "木槿",
    nameEn: "Hibiscus",
    country: "韩国",
    region: "亚洲",
    location: { lat: 37.5665, lng: 126.9780 },
    bloomSeason: "7月-10月",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["白色", "粉色", "紫色", "红色"],
    emoji: "🌺",
    colorHex: "#E91E63",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/The_Botanical_Magazine,_Plate_83_(Volume_3,_1790).png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/木槿",
    brief: "木槿是韩国国花，象征永恒不灭的民族精神。韩国国歌中有木槿花三千里江山的歌词。",
    bloomGuide: "花期长达约100天，每天清晨开花，傍晚凋谢，次日重新开放。",
    viewingTips: "韩国各地公园和街道均可见到木槿，首尔奥林匹克公园的木槿最为集中。",
    category: "木本花卉"
  },
  {
    id: "jasmine_india",
    name: "茉莉花",
    nameEn: "Jasmine",
    country: "印度",
    region: "亚洲",
    location: { lat: 20.5937, lng: 78.9629 },
    bloomSeason: "5月-9月",
    bloomMonths: [5, 6, 7, 8, 9],
    flowerColors: ["白色"],
    emoji: "🌸",
    colorHex: "#FFFFFF",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/JasminumSambac2.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/茉莉花",
    brief: "茉莉花是印度的圣洁之花，常用于神庙装饰和婚礼中。香气被誉为花中皇后。",
    bloomGuide: "花期在夏季，夜晚香气最为浓郁。白色星形小花簇生，泌香四溢。",
    viewingTips: "印度南部泰米尔纳德邦是茉莉花的主产区。",
    category: "木质藤本"
  },

  // ========== 欧洲 ==========
  {
    id: "lavender",
    name: "薰衣草",
    nameEn: "Lavender",
    country: "法国",
    region: "欧洲",
    location: { lat: 43.9493, lng: 5.3966 },
    bloomSeason: "6月-8月",
    bloomMonths: [6, 7, 8],
    flowerColors: ["紫色", "蓝紫色"],
    emoji: "💐",
    colorHex: "#7B68EE",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Single_lavender_flower02.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/薰衣草",
    brief: "薰衣草是普罗旺斯的代名词，每年夏季紫色花海绵延数百公里。香气有舒缓神经的功效。",
    bloomGuide: "盛花期在6月下旬至7月下旬，整片田野呈现迷人的紫色。",
    viewingTips: "法国普罗旺斯的塞南克修道院薰衣草田是世界著名的赏花地。",
    category: "草本花卉"
  },
  {
    id: "rose_uk",
    name: "玫瑰",
    nameEn: "Rose",
    country: "英国",
    region: "欧洲",
    location: { lat: 51.5074, lng: -0.1278 },
    bloomSeason: "5月-9月",
    bloomMonths: [5, 6, 7, 8, 9],
    flowerColors: ["红色", "粉色", "白色", "黄色", "橙色"],
    emoji: "🌹",
    colorHex: "#C62828",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Divlja_ruza_cvijet_270508.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/蔷薇属",
    brief: "玫瑰是英国的国花，是世界上最受欢迎的花卉之一。象征爱情和美丽。",
    bloomGuide: "花期为5-9月，春末夏初最为盛开。玫瑰品种繁多，色彩极为丰富。",
    viewingTips: "英国切尔西花展是世界著名的花卉展。欧洲各大庄园的玫瑰园也是必访之地。",
    category: "木本花卉"
  },
  {
    id: "sunflower",
    name: "向日葵",
    nameEn: "Sunflower",
    country: "法国",
    region: "欧洲",
    location: { lat: 44.1558, lng: 4.7453 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["黄色"],
    emoji: "🌻",
    colorHex: "#FFC107",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Eberndorf_Köcking_Sonnenblumenfeld_Biohof_Tomic_18072014_0792.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/向日葵",
    brief: "向日葵原产于北美洲，是法国的代表性花卉。象征热情、乐观和忠诚。",
    bloomGuide: "花期在夏季，大片向日葵田金黄壮观，花径可达30厘米以上。",
    viewingTips: "法国南部普罗旺斯的向日葵田与薰衣草田并肩而立。",
    category: "草本花卉"
  },
  {
    id: "poppy",
    name: "罂粟花",
    nameEn: "Poppy",
    country: "英国",
    region: "欧洲",
    location: { lat: 51.8787, lng: -0.4200 },
    bloomSeason: "5月-6月",
    bloomMonths: [5, 6],
    flowerColors: ["红色", "橙色", "粉色", "白色", "紫色"],
    emoji: "🩸",
    colorHex: "#FF5722",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Poppies_in_the_Sunset_on_Lake_Geneva.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/虞美人",
    brief: "虞美人是欧洲最美丽的野花之一，大面积盛开时如红色海洋。",
    bloomGuide: "花期在5-6月，花瓣薄如蝉翼，色彩艳丽，花期较短但极为美丽。",
    viewingTips: "英国普通花园和田间地头均可见到。",
    category: "草本花卉"
  },
  {
    id: "hydrangea_france",
    name: "绣球花",
    nameEn: "Hydrangea",
    country: "法国",
    region: "欧洲",
    location: { lat: 47.3770, lng: -1.5428 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["蓝色", "粉色", "紫色", "白色"],
    emoji: "💠",
    colorHex: "#42A5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/紫色繡球花.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/绣球花",
    brief: "绣球花原产于日本，在欧洲广泛栽培。花色因土壤酸碱度而变化。",
    bloomGuide: "花期为6-9月，球形大花头由数十朵小花组成，颜色美艳。",
    viewingTips: "法国布列塔尼、日本箱根是最著名的绣球花观赏地。",
    category: "木本花卉"
  },

  // ========== 美洲 ==========
  {
    id: "dahlia_mexico",
    name: "大丽花",
    nameEn: "Dahlia",
    country: "墨西哥",
    region: "美洲",
    location: { lat: 19.4326, lng: -99.1332 },
    bloomSeason: "7月-10月",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["红色", "紫色", "橙色", "黄色", "白色", "粉色"],
    emoji: "🎯",
    colorHex: "#FF6F00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Dahlia_x_hybrida.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/大丽花",
    brief: "大丽花是墨西哥国花，花型多样，直径可达30厘米以上。",
    bloomGuide: "花期为夏末至秋季，色彩最为丰富。",
    viewingTips: "墨西哥城周边的霍奇米尔科浮岛花园是观赏大丽花的好地方。",
    category: "球根花卉"
  },
  {
    id: "bird_of_paradise",
    name: "天堂鸟",
    nameEn: "Bird of Paradise",
    country: "南非",
    region: "非洲",
    location: { lat: -26.2041, lng: 28.0473 },
    bloomSeason: "9月-5月",
    bloomMonths: [9, 10, 11, 12, 1, 2, 3, 4, 5],
    flowerColors: ["橙色", "蓝色"],
    emoji: "🦜",
    colorHex: "#FF6D00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/The_Botanical_Magazine,_Plate_119_(Volume_4,_1791).png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鹤望兰",
    brief: "天堂鸟花原产于南非，形如热带鸟类，橙色和蓝色的搭配极为独特。",
    bloomGuide: "花期长达数月，每朵花可持续开放数周。",
    viewingTips: "南非开普敦植物园有大规模种植。",
    category: "草本花卉"
  },
  {
    id: "goldenrod_canada",
    name: "加拿大一枝黄花",
    nameEn: "Goldenrod",
    country: "加拿大",
    region: "美洲",
    location: { lat: 45.4215, lng: -75.6972 },
    bloomSeason: "7月-10月",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["黄色", "金黄色"],
    emoji: "🌼",
    colorHex: "#FFD600",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/2016-10-15_Solidago_canadensis,IN_Sasayama,Hyogo_セイタカアワダチソウ(篠山市)_DSCF1299.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/加拿大一枝黄花",
    brief: "加拿大一枝黄花是北美最具代表性的野花，金黄色穗状花序在秋季漫山遍野盛开，是加拿大秋季风景的重要组成部分。",
    bloomGuide: "7-10月开放，金黄色小花密集排列成穗状花序，蜜蜂和蝴蝶的重要蜜源植物。",
    viewingTips: "加拿大安大略省、魁北克省的草原和路边在秋季随处可见大片金黄色花海。",
    category: "草本花卉"
  },

  // ========== 非洲 ==========
  {
    id: "protea",
    name: "帝王花",
    nameEn: "King Protea",
    country: "南非",
    region: "非洲",
    location: { lat: -33.9249, lng: 18.4241 },
    bloomSeason: "3月-9月",
    bloomMonths: [3, 4, 5, 6, 7, 8, 9],
    flowerColors: ["粉色", "红色", "白色"],
    emoji: "👑",
    colorHex: "#E91E63",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Protea_cynaroides_6.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/帝王花",
    brief: "帝王花是南非国花，是世界上最大的花卉之一。象征变化和希望。",
    bloomGuide: "花期在南半球的秋冬季节，花朵巨大，花期持久。",
    viewingTips: "南非开普半岛国家公园内野生帝王花极为壮观。",
    category: "木本花卉"
  },

  // ========== 大洋洲 ==========
  {
    id: "kangaroo_paw",
    name: "袋鼠花",
    nameEn: "Kangaroo Paw",
    country: "澳大利亚",
    region: "大洋洲",
    location: { lat: -31.9505, lng: 115.8605 },
    bloomSeason: "8月-11月",
    bloomMonths: [8, 9, 10, 11],
    flowerColors: ["红色", "绿色", "黄色", "橙色"],
    emoji: "🦘",
    colorHex: "#F44336",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Anigozanthos.flavidus1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/袋鼠花",
    brief: "袋鼠花是西澳大利亚州的州花，因其花形酷似袋鼠的爪子而得名。",
    bloomGuide: "花期在春夏季，管状绒毛花朵簇生，色彩鲜艳。",
    viewingTips: "西澳大利亚的金花之路是观赏袋鼠花的最佳路线。",
    category: "草本花卉"
  },
  {
    id: "waratah",
    name: "瓦拉塔花",
    nameEn: "Waratah",
    country: "澳大利亚",
    region: "大洋洲",
    location: { lat: -33.8688, lng: 151.2093 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["红色"],
    emoji: "🌺",
    colorHex: "#D32F2F",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Telopea_speciosissima_suellen.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/瓦拉塔花",
    brief: "瓦拉塔花是新南威尔士州的州花，澳大利亚土著原住民的重要文化象征。",
    bloomGuide: "花期在春季，鲜艳的红色花球在绿色林地中格外显眼。",
    viewingTips: "蓝山国家公园是观赏野生瓦拉塔花的最佳地点。",
    category: "木本花卉"
  },

  // ========== 其他 ==========
  {
    id: "plumeria",
    name: "鸡蛋花",
    nameEn: "Plumeria",
    country: "夏威夷",
    region: "美洲",
    location: { lat: 21.3069, lng: -157.8583 },
    bloomSeason: "3月-10月",
    bloomMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    flowerColors: ["白色", "黄色", "粉色", "红色"],
    emoji: "🏝️",
    colorHex: "#FFEE58",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Plumeria_rubra-4.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鸡蛋花",
    brief: "鸡蛋花是夏威夷的代表性花卉，常用于制作花环。",
    bloomGuide: "热带地区几乎全年开花。花香浓郁优雅。",
    viewingTips: "夏威夷各岛均有大量鸡蛋花树。",
    category: "木本花卉"
  },
  {
    id: "water_lily",
    name: "睡莲",
    nameEn: "Water Lily",
    country: "法国",
    region: "欧洲",
    location: { lat: 49.0766, lng: 1.8671 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["白色", "粉色", "紫色", "黄色"],
    emoji: "🎨",
    colorHex: "#CE93D8",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Nymphaea_alba.001_-_Breendonk.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/睡莲",
    brief: "睡莲是水上花卉的经典代表，莫奈的名画使其举世闻名。",
    bloomGuide: "花期在夏季，白天开放，夜晚或阴雨天闭合。",
    viewingTips: "法国吉维尼的莫奈花园是观赏睡莲的圣地。",
    category: "水生花卉"
  },
  {
    id: "forget_me_not",
    name: "勿忘我",
    nameEn: "Forget-Me-Not",
    country: "德国",
    region: "欧洲",
    location: { lat: 52.5200, lng: 13.4050 },
    bloomSeason: "4月-6月",
    bloomMonths: [4, 5, 6],
    flowerColors: ["蓝色", "粉色", "白色"],
    emoji: "💙",
    colorHex: "#1565C0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Myosotis_asiatica_45805547.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/勿忘草",
    brief: "勿忘我是德国传统爱情花卉，象征永恒的爱与纪念。",
    bloomGuide: "花期在春末夏初，天蓝色的五瓣小花密密麻麻开满枝头。",
    viewingTips: "欧洲各地公园、花园和野外均可见到。",
    category: "草本花卉"
  },
  {
    id: "camellia",
    name: "山茶花",
    nameEn: "Camellia",
    country: "中国",
    region: "亚洲",
    location: { lat: 25.0440, lng: 102.7082 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["红色", "粉色", "白色"],
    emoji: "🫖",
    colorHex: "#E53935",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Camellia_sasanqua1JAM343.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/山茶花",
    brief: "山茶花是云南省花，也是中国十大名花之一。云南山茶冠天下。",
    bloomGuide: "花期在冬末春初，花朵硕大，耐寒性强。",
    viewingTips: "云南昆明、腾冲、丽江有许多古山茶树。",
    category: "木本花卉"
  },
  {
    id: "narcissus",
    name: "水仙花",
    nameEn: "Narcissus",
    country: "中国",
    region: "亚洲",
    location: { lat: 24.4798, lng: 118.0819 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["白色", "黄色"],
    emoji: "🪞",
    colorHex: "#FFF9C4",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Jonquil_flowers06.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/水仙属",
    brief: "水仙花是中国十大名花之一，被誉为凌波仙子。",
    bloomGuide: "花期在冬末春初，在水盘中即可开花。",
    viewingTips: "福建漳州是中国水仙花的主产区。",
    category: "球根花卉"
  },
  {
    id: "osmanthus",
    name: "桂花",
    nameEn: "Osmanthus",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.2741, lng: 120.1551 },
    bloomSeason: "9月-10月",
    bloomMonths: [9, 10],
    flowerColors: ["金黄色", "橙色", "白色"],
    emoji: "🌕",
    colorHex: "#FF8F00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Osmanthus_heterophyllus1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/木犀",
    brief: "桂花是中国著名传统花卉，香气被称为天香。与中秋节密切相关。",
    bloomGuide: "花期在秋季，虽不起眼但香气远飘数里。",
    viewingTips: "杭州满觉陇是著名赏桂胜地。",
    category: "木本花卉"
  },
  {
    id: "bauhinia",
    name: "洋紫荆",
    nameEn: "Bauhinia",
    country: "中国香港",
    region: "亚洲",
    location: { lat: 22.3193, lng: 114.1694 },
    bloomSeason: "11月-3月",
    bloomMonths: [11, 12, 1, 2, 3],
    flowerColors: ["紫红色", "粉色"],
    emoji: "🟣",
    colorHex: "#C2185B",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bauhinia_divaricata.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/洋紫荆",
    brief: "洋紫荆是香港的市花，香港区旗上就有洋紫荆花朵。",
    bloomGuide: "花期从11月延续到次年3月，花朵硕大艳丽。",
    viewingTips: "香港公园、维多利亚公园均有大量洋紫荆。",
    category: "木本花卉"
  },
  {
    id: "peach_blossom",
    name: "桃花",
    nameEn: "Peach Blossom",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.2742, lng: 120.1551 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["粉色", "白色", "深粉色"],
    emoji: "🍑",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Nectarine_Fruit_Development.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/桃",
    brief: "桃花在中国文化中象征爱情、长寿和好运。桃花源记让桃花成为理想仙境的象征。",
    bloomGuide: "花期在3-4月，先叶开放，花朵粉嫩可爱。",
    viewingTips: "北京、杭州、上海都有著名赏花地点。",
    category: "木本花卉"
  },
  {
    id: "rape_flower",
    name: "油菜花",
    nameEn: "Canola Flower",
    country: "中国",
    region: "亚洲",
    location: { lat: 25.0480, lng: 100.2170 },
    bloomSeason: "1月-4月",
    bloomMonths: [1, 2, 3, 4],
    flowerColors: ["黄色"],
    emoji: "💛",
    colorHex: "#FDD835",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Brassica_napus_-_Köhler–s_Medizinal-Pflanzen-169.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/油菜",
    brief: "油菜花是中国南方春季最具代表性的风景。云南罗平、江西婺源最为著名。",
    bloomGuide: "花期因地区和气候不同而延续数月。大规模种植时极为壮观。",
    viewingTips: "云南罗平、江西婺源、陕西汉中是中国三大著名油菜花观赏地。",
    category: "草本花卉"
  },
  {
    id: "forsythia",
    name: "连翘",
    nameEn: "Forsythia",
    country: "韩国",
    region: "亚洲",
    location: { lat: 37.5665, lng: 126.9780 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["黄色"],
    emoji: "⭐",
    colorHex: "#FFCA28",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Forsythia_suspensa_SZ3.png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/连翘",
    brief: "连翘是韩国最受喜爱的春花之一，被誉为韩国春天的使者。金黄色的花朵在叶子萌发前就已满枝盛开。",
    bloomGuide: "花先于叶开放，金黄色，满枝盛开时热烈而张扬。",
    viewingTips: "韩国首尔的南山公园春季连翘盛开。",
    category: "木本花卉"
  },
  {
    id: "morning_glory",
    name: "牵牛花",
    nameEn: "Morning Glory",
    country: "日本",
    region: "亚洲",
    location: { lat: 35.6762, lng: 139.6503 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["蓝色", "紫色", "粉色", "白色", "红色"],
    emoji: "📯",
    colorHex: "#3F51B5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Ipomoea_nil_Akatsukinoumi1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/牵牛花",
    brief: "牵牛花是日本江户时代最受欢迎的观赏植物，品种多样。",
    bloomGuide: "花期在夏季，每天清晨开花，午后凋谢，故英文名为Morning Glory。",
    viewingTips: "东京入谷的牵牛花市是日本最著名的牵牛花集市。",
    category: "草本藤本"
  },
  {
    id: "jacaranda",
    name: "蓝楹花",
    nameEn: "Jacaranda",
    country: "巴西",
    region: "美洲",
    location: { lat: -23.5505, lng: -46.6333 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["紫色", "蓝紫色"],
    emoji: "☔",
    colorHex: "#7E57C2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Jacaranda_mimosifolia_flowers_and_leaves.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/蓝花楹",
    brief: "蓝楹花原产于巴西，满树盛开的蓝紫色花朵如紫色烟雾，是世界最美丽的观花树种之一。",
    bloomGuide: "花期在春季，开花时叶子往往还未完全展开，落花时铺满地面形成紫色花毯。",
    viewingTips: "南非比勒陀利亚被称为蓝楹花之城，每年10月满城紫花盛开。",
    category: "木本花卉"
  },
  {
    id: "lupine",
    name: "鲁冰花",
    nameEn: "Lupine",
    country: "新西兰",
    region: "大洋洲",
    location: { lat: -44.6519, lng: 168.3461 },
    bloomSeason: "11月-1月",
    bloomMonths: [11, 12, 1],
    flowerColors: ["紫色", "粉色", "红色", "黄色", "白色"],
    emoji: "🪻",
    colorHex: "#673AB7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lupinus_polyphyllus_526960203.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/羽扇豆属",
    brief: "鲁冰花在新西兰的麦肯奇地区已成为最具代表性的景观花卉。每年夏季数百万株花在库克山脚下盛开。",
    bloomGuide: "花期在南半球的夏初，挺立的穗状花序高达1米，颜色从紫色到黄色各异。",
    viewingTips: "新西兰麦肯奇盆地、特卡波湖是观赏鲁冰花的最佳地点。",
    category: "草本花卉"
  },
  {
    id: "mountain_laurel",
    name: "山月桂",
    nameEn: "Mountain Laurel",
    country: "美国",
    region: "美洲",
    location: { lat: 40.0583, lng: -74.4057 },
    bloomSeason: "5月-6月",
    bloomMonths: [5, 6],
    flowerColors: ["粉色", "白色", "红色"],
    emoji: "🌸",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Kalmia_Latifolia.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/山月桂",
    brief: "山月桂是美国宾夕法尼亚和康涅狄格州的州花，花朵精致如五角星形，粉白相间，是北美东部山地最美丽的野生灌木之一。",
    bloomGuide: "5-6月盛开，花朵呈杯状，粉色花瓣上点缀深色斑点，花苞如精致的灯笼，开放时优雅迷人。",
    viewingTips: "美国阿巴拉契亚山脉、大烟山国家公园是观赏野生山月桂的最佳地点。",
    category: "木本花卉"
  },
  {
    id: "iris_france",
    name: "鸢尾",
    nameEn: "Iris",
    country: "法国",
    region: "欧洲",
    location: { lat: 45.7640, lng: 4.8357 },
    bloomSeason: "4月-6月",
    bloomMonths: [4, 5, 6],
    flowerColors: ["紫色", "蓝色", "白色", "黄色"],
    emoji: "⚜️",
    colorHex: "#7E57C2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Kosaciec_01.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鸢尾属",
    brief: "鸢尾花是法国的国花象征，法语名Fleur-de-lis是法国王室的传统标志。",
    bloomGuide: "花期在4-6月，花朵形态复杂优美，香气宜人。",
    viewingTips: "佛罗伦萨的鸢尾花园每年5月开放。",
    category: "球根花卉"
  },
  {
    id: "edelweiss",
    name: "雪绒花",
    nameEn: "Edelweiss",
    country: "瑞士",
    region: "欧洲",
    location: { lat: 46.8182, lng: 8.2275 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["白色"],
    emoji: "🌸",
    colorHex: "#F5F5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Alpen_Edelweiß,_Leontopodium_alpinum_2.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/雪绒花",
    brief: "雪绒花是阿尔卑斯山的象征，奥地利和瑞士的国花。生长在高山岩壁，因稀有而珍贵，象征纯洁和勇气。",
    bloomGuide: "花期在7-9月，星形白色花朵覆满银白色绒毛，在岩壁上傲然绽放。",
    viewingTips: "在瑞士、奥地利的高山徒步路线上可以见到野生雪绒花。",
    category: "草本花卉"
  },
  {
    id: "sakura_taiwan",
    name: "台湾山樱",
    nameEn: "Taiwan Cherry",
    country: "中国台湾",
    region: "亚洲",
    location: { lat: 24.1477, lng: 120.6736 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["深粉色", "红色"],
    emoji: "🩷",
    colorHex: "#E91E63",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Hikanzakura.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/台湾樱花",
    brief: "台湾山樱花色深粉至深红，是台湾春节期间最重要的观花植物。",
    bloomGuide: "花期在1-3月，深粉色花朵点缀于青翠山林之间。",
    viewingTips: "台湾阿里山、武陵农场是赏台湾山樱的最佳地点。",
    category: "木本花卉"
  },
  {
    id: "cyclamen",
    name: "仙客来",
    nameEn: "Cyclamen",
    country: "以色列",
    region: "亚洲",
    location: { lat: 32.0853, lng: 34.7818 },
    bloomSeason: "11月-3月",
    bloomMonths: [11, 12, 1, 2, 3],
    flowerColors: ["粉色", "红色", "白色", "紫色"],
    emoji: "🦋",
    colorHex: "#F06292",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/The_Botanical_Magazine,_Plate_44_(Volume_2,_1788).png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/仙客来",
    brief: "仙客来是以色列的国花。其独特的翻折花瓣形如翩翩蝴蝶。",
    bloomGuide: "花期在冬春季，耐寒，可在室内低温环境下持续开放数月。",
    viewingTips: "以色列加利利山区的野生仙客来林在1-2月极为壮观。",
    category: "球根花卉"
  },
  {
    id: "foxglove",
    name: "洋地黄",
    nameEn: "Foxglove",
    country: "爱尔兰",
    region: "欧洲",
    location: { lat: 53.1424, lng: -7.6921 },
    bloomSeason: "6月-8月",
    bloomMonths: [6, 7, 8],
    flowerColors: ["紫色", "白色", "粉色"],
    emoji: "🌼",
    colorHex: "#9C27B0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Digitalis-stora_hultrum.sweden-24.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/毛地黄",
    brief: "洋地黄是爱尔兰和英国山地最具代表性的野花，高大的穗状花序，内有深色斑点，极具辨识度。",
    bloomGuide: "花期在夏季，花穗高达1-2米，花朵从下向上依次开放。",
    viewingTips: "爱尔兰西海岸的科纳玛拉荒野有大量野生洋地黄。",
    category: "草本花卉"
  },
  {
    id: "rhododendron",
    name: "高山杜鹃",
    nameEn: "Rhododendron",
    country: "尼泊尔",
    region: "亚洲",
    location: { lat: 27.7172, lng: 85.3240 },
    bloomSeason: "3月-5月",
    bloomMonths: [3, 4, 5],
    flowerColors: ["红色", "粉色", "白色", "紫色"],
    emoji: "🏔️",
    colorHex: "#E53935",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Alpenroos.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/杜鹃花属",
    brief: "高山杜鹃是尼泊尔国花，广泛分布于喜马拉雅山脉。每年春季，山坡上大片杜鹃花盛开。",
    bloomGuide: "花期在春季，随海拔升高而推迟，与白雪皑皑的喜马拉雅雪峰交相辉映。",
    viewingTips: "尼泊尔蓝塘国家公园是观赏高山杜鹃的圣地。",
    category: "木本花卉"
  },
  {
    id: "oleander",
    name: "夹竹桃",
    nameEn: "Oleander",
    country: "希腊",
    region: "欧洲",
    location: { lat: 37.9838, lng: 23.7275 },
    bloomSeason: "5月-10月",
    bloomMonths: [5, 6, 7, 8, 9, 10],
    flowerColors: ["粉色", "红色", "白色", "黄色"],
    emoji: "🌷",
    colorHex: "#FF80AB",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Nerium_oleander_flowers_leaves.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/夹竹桃",
    brief: "夹竹桃是地中海地区最常见的观花植物，在希腊、西班牙街道和庭院中随处可见。",
    bloomGuide: "花期从春末延续至秋季，是地中海夏季的标志性花卉。",
    viewingTips: "希腊圣托里尼岛、米科诺斯岛的白色建筑配上粉色夹竹桃构成标志性地中海美景。",
    category: "木本花卉"
  },
  {
    id: "cosmos_japan",
    name: "波斯菊",
    nameEn: "Cosmos",
    country: "日本",
    region: "亚洲",
    location: { lat: 35.3592, lng: 138.7275 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["粉色", "白色", "深红色"],
    emoji: "✨",
    colorHex: "#FF69B4",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cosmos_bipinnatus_pink,_Burdwan,_West_Bengal,_India_10_01_2013.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/秋英",
    brief: "波斯菊是日本秋季最具代表性的野花，如今已成为日本秋天风景的重要组成部分。",
    bloomGuide: "花期为9-11月，大面积种植时如粉色海洋，随风摇曳，美不胜收。",
    viewingTips: "昭和纪念公园有大规模波斯菊花田，秋季是赏花旺季。",
    category: "草本花卉"
  },
  {
    id: "cactus_flower",
    name: "仙人掌花",
    nameEn: "Cactus Flower",
    country: "墨西哥",
    region: "美洲",
    location: { lat: 23.6345, lng: -102.5528 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["红色", "粉色", "黄色", "橙色", "白色"],
    emoji: "🌵",
    colorHex: "#FF5722",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Pereskia_aculeata4_cropped.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/仙人掌",
    brief: "仙人掌花是沙漠中令人惊叹的生命奇迹，色彩鲜艳，象征顽强的生命力。",
    bloomGuide: "多在夜间开放，花期较短但颜色极为艳丽。",
    viewingTips: "美国亚利桑那州萨瓜罗国家公园是观赏沙漠花卉的理想目的地。",
    category: "多肉植物"
  },
  {
    id: "freesia",
    name: "香雪兰",
    nameEn: "Freesia",
    country: "南非",
    region: "非洲",
    location: { lat: -33.0000, lng: 26.0000 },
    bloomSeason: "2月-4月",
    bloomMonths: [2, 3, 4],
    flowerColors: ["白色", "黄色", "粉色", "紫色", "橙色"],
    emoji: "🌸",
    colorHex: "#FFF176",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Freesia.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/香雪兰属",
    brief: "香雪兰原产于南非，是世界最重要的切花之一。花香清新优雅。",
    bloomGuide: "花期在早春，香气馥郁持久。",
    viewingTips: "南非开普地区是香雪兰的原产地。",
    category: "球根花卉"
  },
  {
    id: "bluebell",
    name: "蓝铃花",
    nameEn: "Bluebell",
    country: "英国",
    region: "欧洲",
    location: { lat: 53.0000, lng: -2.0000 },
    bloomSeason: "4月-5月",
    bloomMonths: [4, 5],
    flowerColors: ["蓝紫色"],
    emoji: "🪻",
    colorHex: "#5C6BC0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Hyacinth-spring.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/风信子属",
    brief: "蓝铃花是英国最具代表性的春季花卉，每年春天在橡树林中大片盛开，将整个森林染成神秘的蓝紫色。",
    bloomGuide: "花期约在4月中旬至5月中旬，花形如小铃铛，大片盛开时蔚为壮观。",
    viewingTips: "英格兰和威尔士的古老橡树林是欣赏蓝铃花的最佳地点。",
    category: "球根花卉"
  },
  {
    id: "rafflesia",
    name: "大王花",
    nameEn: "Rafflesia",
    country: "印度尼西亚",
    region: "亚洲",
    location: { lat: 0.7893, lng: 113.9213 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["红色", "橙色", "棕红色"],
    emoji: "👹",
    colorHex: "#B71C1C",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Rafflesia_arnoldii,_Sumatra.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/大花草属",
    brief: "大王花是世界上最大的单朵花，直径可达1米，是印度尼西亚的国花之一。",
    bloomGuide: "花期极短，仅开放4-5天，一生只开一次花。",
    viewingTips: "印度尼西亚婆罗洲、苏门答腊热带雨林是观赏大王花的主要地点。",
    category: "寄生植物"
  },
  {
    id: "agapanthus",
    name: "百子莲",
    nameEn: "Agapanthus",
    country: "南非",
    region: "非洲",
    location: { lat: -33.9249, lng: 18.4241 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["蓝色", "紫色", "白色"],
    emoji: "🫧",
    colorHex: "#1E88E5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Agapanthus_africanus1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/百子莲属",
    brief: "百子莲原产于南非，花朵蓝紫色，球形花序优雅迷人，是世界各地广泛栽培的花卉。",
    bloomGuide: "花期在夏季，球形伞状花序由数十朵漏斗形小花组成，花茎高挺。",
    viewingTips: "南非开普半岛、葡萄牙阿佐雷斯群岛的百子莲花盛开时极为壮观。",
    category: "球根花卉"
  },
  {
    id: "phalaenopsis",
    name: "蝴蝶兰",
    nameEn: "Moth Orchid",
    country: "中国台湾",
    region: "亚洲",
    location: { lat: 23.6978, lng: 120.9605 },
    bloomSeason: "12月-4月",
    bloomMonths: [12, 1, 2, 3, 4],
    flowerColors: ["白色", "粉色", "紫色", "黄色"],
    emoji: "🌸",
    colorHex: "#E1BEE7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/蝴蝶兰属",
    brief: "蝴蝶兰是台湾最重要的花卉产业，每年出口数千万株。花形优美如蝴蝶飞舞。",
    bloomGuide: "花期主要在冬春季节，每株可同时开放数十朵花。",
    viewingTips: "台北国际兰展每年2月举办。",
    category: "附生兰花"
  },
  {
    id: "catleya_orchid",
    name: "嘉德利亚兰",
    nameEn: "Cattleya Orchid",
    country: "巴西",
    region: "美洲",
    location: { lat: -14.2350, lng: -51.9253 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["紫色", "粉色", "白色", "橙色"],
    emoji: "🪻",
    colorHex: "#AB47BC",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cattleya_labiata_Orchi_1013.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/卡特兰属",
    brief: "嘉德利亚兰是热带兰花中最华丽的类群，花朵巨大，被誉为兰花女王。",
    bloomGuide: "主要花期在秋季，花朵可持续开放2-4周，香气馥郁。",
    viewingTips: "巴西圣保罗的国际兰花展是世界规模最大的兰花展。",
    category: "附生兰花"
  },
  {
    id: "ginger_flower",
    name: "姜花",
    nameEn: "Ginger Lily",
    country: "印度",
    region: "亚洲",
    location: { lat: 10.8505, lng: 76.2711 },
    bloomSeason: "8月-10月",
    bloomMonths: [8, 9, 10],
    flowerColors: ["白色", "黄色"],
    emoji: "🌿",
    colorHex: "#FFFDE7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Hedychium_coronarium_(2097558711).jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/姜花属",
    brief: "姜花是印度喀拉拉邦的州花，花朵洁白芬芳，是世界上最香的花之一。",
    bloomGuide: "花期在秋季，香气极为浓郁，在夜晚和清晨最为明显。",
    viewingTips: "印度喀拉拉邦的山地和溪边野生姜花最为茂盛。",
    category: "草本花卉"
  },
  {
    id: "queen_of_night",
    name: "昙花",
    nameEn: "Queen of the Night",
    country: "中美洲",
    region: "美洲",
    location: { lat: 15.7835, lng: -90.2308 },
    bloomSeason: "夏秋",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["白色"],
    emoji: "🌙",
    colorHex: "#ECEFF1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/3_blooms_of_Epiphyllum_oxypetalum.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/昙花",
    brief: "昙花每年仅在夜晚开花一次，花期只有数小时。昙花一现成为了美好而短暂之物的代名词。",
    bloomGuide: "每年夏秋季节开花，通常在傍晚开放，花朵大而洁白，清晨凋谢。",
    viewingTips: "在家中培育昙花是很多花卉爱好者的兴趣，需守候整夜才能目睹其绽放的刹那。",
    category: "多肉植物"
  },
  {
    id: "snowdrop_germany",
    name: "雪花莲",
    nameEn: "Snowdrop",
    country: "德国",
    region: "欧洲",
    location: { lat: 50.1109, lng: 8.6821 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["白色", "绿色"],
    emoji: "🌸",
    colorHex: "#F5F5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Galanthus_nivalis.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/雪花莲",
    brief: "雪花莲是欧洲最早报春的花卉之一，在冰雪未融之际便探出白色花朵，象征着春天的到来和希望。在德国被视为早春的使者。",
    bloomGuide: "1-3月在残雪中绽放，白色钟形花朵下垂，花瓣上有精致的绿色斑纹，小巧玲珑。",
    viewingTips: "德国法兰克福植物园、英国巴斯附近的古老庄园林地是欣赏雪花莲花海的绝佳地点。",
    category: "球根花卉"
  },
  {
    id: "heliconia",
    name: "赫蕉",
    nameEn: "Heliconia",
    country: "哥斯达黎加",
    region: "美洲",
    location: { lat: 9.7489, lng: -83.7534 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["红色", "橙色", "黄色"],
    emoji: "🌺",
    colorHex: "#FF3D00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Heliconia_latispatha_(Starwiz).jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/蝎尾蕉属",
    brief: "赫蕉是中美洲热带雨林的代表性花卉，鲜艳的橙红色苞片形态奇特，如同悬挂的龙虾爪子。",
    bloomGuide: "热带地区几乎全年可见，花序大而奇特，颜色鲜艳持久。",
    viewingTips: "哥斯达黎加热带雨林、新加坡植物园都有大量赫蕉展示。",
    category: "草本花卉"
  },
  {
    id: "bromeliad",
    name: "凤梨花",
    nameEn: "Bromeliad",
    country: "巴西",
    region: "美洲",
    location: { lat: -15.7801, lng: -47.9292 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["红色", "橙色", "紫色", "粉色", "黄色"],
    emoji: "🍍",
    colorHex: "#D84315",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Ananas-wilde.jpeg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/凤梨科",
    brief: "凤梨花是热带雨林的典型植物，原产于南美洲热带地区。其苞片鲜艳持久，极具装饰价值。",
    bloomGuide: "室内种植几乎全年都可开花，苞片颜色鲜艳，观赏期可长达数月。",
    viewingTips: "巴西里约热内卢的植物园有丰富的本土凤梨科植物收藏。",
    category: "草本花卉"
  },
  {
    id: "dok_mali_thailand",
    name: "泰国茉莉",
    nameEn: "Thai Jasmine",
    country: "泰国",
    region: "亚洲",
    location: { lat: 13.7563, lng: 100.5018 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["白色"],
    emoji: "🌸",
    colorHex: "#FFFFFF",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Arabian_jasmin,_Tunisia_2010.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/双瓣茉莉",
    brief: "泰国茉莉（Dok Mali）是泰国的国花，洁白芳香，象征纯洁与母爱。每年母亲节泰国人向母亲献上茉莉花环以表敬意。",
    bloomGuide: "热带气候下全年开放，白色双瓣花朵散发清甜芬芳，傍晚至夜间香气最为浓郁。",
    viewingTips: "曼谷花市帕克隆塔拉花市是泰国最大的鲜花市场，茉莉花环是最常见的花艺制品。",
    category: "木本花卉"
  },
  {
    id: "pear_blossom",
    name: "梨花",
    nameEn: "Pear Blossom",
    country: "中国",
    region: "亚洲",
    location: { lat: 40.4177, lng: 91.0287 },
    bloomSeason: "3月-5月",
    bloomMonths: [3, 4, 5],
    flowerColors: ["白色"],
    emoji: "🍐",
    colorHex: "#F5F5F5",
    wikiImage: "https://p3.itc.cn/images01/20230102/9a38a0dbedfd45d885bf02a79c24e41b.jpeg",
    wikiUrl: "https://zh.wikipedia.org/wiki/梨",
    brief: "梨花洁白如雪，清香素雅，是中国传统诗词中的重要意象。新疆库尔勒的梨花最为著名。",
    bloomGuide: "花期在3-5月，五瓣白花，清雅秀丽，大片梨花盛开时如白雪覆盖。",
    viewingTips: "新疆库尔勒、陕西蒲城是著名的梨花观赏地，常举办梨花旅游节。",
    category: "木本花卉"
  },

  // ========== 中国新增 30 种 ==========
  {
    id: "magnolia_china",
    name: "玉兰",
    nameEn: "Magnolia",
    country: "中国",
    region: "亚洲",
    location: { lat: 31.2304, lng: 121.4737 },
    bloomSeason: "2月-3月",
    bloomMonths: [2, 3],
    flowerColors: ["白色", "粉色"],
    emoji: "🕊️",
    colorHex: "#FAF0E6",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Yulan_1.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/玉兰",
    brief: "玉兰花早春先叶开放，洁白如玉，清香怡人，是上海市花。花大且芳香，是中国古典园林中的重要观赏树种。",
    bloomGuide: "早春2-3月先花后叶，白色大花朵如玉雕，清晨香气尤为浓郁。",
    viewingTips: "上海人民广场、苏州拙政园、南京明孝陵是赏玉兰的好地方。",
    category: "木本花卉"
  },
  {
    id: "azalea_china",
    name: "杜鹃花",
    nameEn: "Azalea",
    country: "中国",
    region: "亚洲",
    location: { lat: 26.8206, lng: 100.2258 },
    bloomSeason: "4月-6月",
    bloomMonths: [4, 5, 6],
    flowerColors: ["红色", "粉色", "紫色", "白色"],
    emoji: "🌺",
    colorHex: "#E91E63",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Alpenroos.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/杜鹃花",
    brief: "杜鹃花是中国十大名花之一，品种超过900种，云南是世界杜鹃花最丰富的地区，高黎贡山上古杜鹃树已有数百年历史。",
    bloomGuide: "4-6月盛开，花色艳丽，满山红遍，云南高海拔地区的野生杜鹃尤为壮观。",
    viewingTips: "云南腾冲高黎贡山、四川西岭雪山、贵州百里杜鹃是赏杜鹃的绝佳地点。",
    category: "木本花卉"
  },
  {
    id: "narcissus_china",
    name: "水仙",
    nameEn: "Narcissus",
    country: "中国",
    region: "亚洲",
    location: { lat: 24.4798, lng: 118.0894 },
    bloomSeason: "12月-2月",
    bloomMonths: [12, 1, 2],
    flowerColors: ["白色", "黄色"],
    emoji: "🎍",
    colorHex: "#FFFDE7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Narcissus_Tazetta_Var_Chinensis_日本水仙_(131230379).jpeg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/水仙",
    brief: "中国水仙是福建漳州的著名特产，凌波仙子般在水中生长，清香淡雅，是元旦春节期间的传统年花。",
    bloomGuide: "冬季12月至次年2月开放，六片白色花瓣，中心黄色副冠，清香怡人。",
    viewingTips: "福建漳州水仙花基地是世界最大的水仙花生产地，每年举办水仙花节。",
    category: "球根花卉"
  },
  {
    id: "apricot_blossom",
    name: "杏花",
    nameEn: "Apricot Blossom",
    country: "中国",
    region: "亚洲",
    location: { lat: 40.8518, lng: 111.7481 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["粉色", "白色"],
    emoji: "🌸",
    colorHex: "#F8BBD9",
    wikiImage: "https://gips2.baidu.com/it/u=3974222926,104857903&fm=3074&app=3074&f=JPEG",
    wikiUrl: "https://zh.wikipedia.org/wiki/杏",
    brief: "杏花是中国北方春天最早盛开的花木之一，粉白相间，如云似霞。新疆伊犁杏花沟每年春季吸引无数摄影爱好者，是中国最壮观的杏花景观。",
    bloomGuide: "3-4月先叶开放，花朵粉白色，单瓣五片，清雅素洁，大面积盛开时如粉色云霞铺满山谷。",
    viewingTips: "新疆伊犁杏花沟、北京凤凰岭、山西运城是著名的赏杏花地点。",
    category: "木本花卉"
  },
  {
    id: "crape_myrtle",
    name: "紫薇",
    nameEn: "Crape Myrtle",
    country: "中国",
    region: "亚洲",
    location: { lat: 32.0603, lng: 118.7969 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["紫色", "粉色", "红色", "白色"],
    emoji: "🪻",
    colorHex: "#CE93D8",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/LagerstroemiaIndica3.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/紫薇",
    brief: "紫薇花期长达百日，故有\"百日红\"之称，是夏秋季节最重要的观赏花木之一，南京城内古紫薇树众多。",
    bloomGuide: "6-9月持续开放，花朵皱缩，色彩丰富，花期极长，树皮光滑，俗称\"痒痒树\"。",
    viewingTips: "南京总统府、扬州瘦西湖、各地古典园林中广泛种植，夏季最为壮观。",
    category: "木本花卉"
  },
  {
    id: "winter_sweet",
    name: "腊梅",
    nameEn: "Winter Sweet",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.6587, lng: 104.0657 },
    bloomSeason: "12月-2月",
    bloomMonths: [12, 1, 2],
    flowerColors: ["金黄色"],
    emoji: "🏮",
    colorHex: "#FFD54F",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Chimonanthus_praecox_(18248235374).jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/腊梅",
    brief: "腊梅在严冬独自绽放，蜡质黄花散发幽香，是中国最受喜爱的冬季花卉之一，被誉为\"雪中送炭\"的吉祥花木。",
    bloomGuide: "12月至次年2月开放，蜡质花朵金黄晶莹，清香远溢，在冰雪中傲然盛开，气质高洁。",
    viewingTips: "成都人民公园、武汉东湖梅园、重庆南山植物园是赏腊梅的好地方。",
    category: "木本花卉"
  },
  {
    id: "daylily_china",
    name: "萱草",
    nameEn: "Daylily",
    country: "中国",
    region: "亚洲",
    location: { lat: 36.0651, lng: 103.8343 },
    bloomSeason: "5月-8月",
    bloomMonths: [5, 6, 7, 8],
    flowerColors: ["橙色", "黄色", "红色"],
    emoji: "🧡",
    colorHex: "#FF9800",
    wikiImage: "https://so1.360tres.com/t019c2b4618e6d37b35.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/萱草",
    brief: "萱草是中国传统的\"忘忧草\"，花朵金黄橙红，象征忘忧与慈母之爱。甘肃张掖是著名的萱草产地，漫山遍野金色花海。",
    bloomGuide: "5-8月开放，每朵花仅开一天，但不断有新花绽放，花期绵长。",
    viewingTips: "甘肃张掖大斜沟、山西大同黄花城、陕西秦岭等地有壮观的野生萱草花海。",
    category: "草本花卉"
  },
  {
    id: "cotton_rose",
    name: "木芙蓉",
    nameEn: "Cotton Rose",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.6587, lng: 104.0657 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["粉色", "白色", "红色"],
    emoji: "🌸",
    colorHex: "#F06292",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Mufurong1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/木芙蓉",
    brief: "木芙蓉是成都市花，晨开白花，午转粉红，暮色深红，一日三变，故又名\"三醉芙蓉\"，是秋季最美丽的观赏花木之一。",
    bloomGuide: "9-11月开放，花大色美，单瓣或重瓣，一日之内颜色由白变粉再变红，变化神奇。",
    viewingTips: "成都人民公园、杜甫草堂是著名赏芙蓉之处，四川各地秋季随处可见。",
    category: "木本花卉"
  },
  {
    id: "garden_balsam",
    name: "凤仙花",
    nameEn: "Garden Balsam",
    country: "中国",
    region: "亚洲",
    location: { lat: 28.2278, lng: 112.9388 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["红色", "粉色", "白色", "紫色"],
    emoji: "💅",
    colorHex: "#EC407A",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Impatiens_balsamina0.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/凤仙花",
    brief: "凤仙花是中国民间最熟悉的夏季花卉，古代女子用其汁液染红指甲，故又名\"指甲花\"。花朵多姿，颜色鲜艳，深受喜爱。",
    bloomGuide: "6-9月开放，花朵腋生，颜色多样，果实成熟后轻触即弹裂射出种子，极具趣味性。",
    viewingTips: "湖南湘西、贵州苗乡的凤仙花与民族文化密切相关，当地染布传统延续至今。",
    category: "草本花卉"
  },
  {
    id: "tiger_lily",
    name: "卷丹百合",
    nameEn: "Tiger Lily",
    country: "中国",
    region: "亚洲",
    location: { lat: 31.8639, lng: 117.2808 },
    bloomSeason: "7月-8月",
    bloomMonths: [7, 8],
    flowerColors: ["橙色", "红色"],
    emoji: "🐯",
    colorHex: "#FF7043",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lilium_lancifolium.jpeg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/卷丹",
    brief: "卷丹是中国原产的著名百合，橙红色花瓣向后卷曲，点缀深色斑点，气质华贵，是中国百合属植物中最具代表性的品种之一。",
    bloomGuide: "7-8月开放，花朵下垂，六片橙红花瓣反卷，布满紫黑色斑点，香气浓郁，球茎可食用。",
    viewingTips: "安徽金寨、湖南湘西山区可见野生卷丹，江苏沭阳是著名的百合花种植基地。",
    category: "球根花卉"
  },
  {
    id: "silk_tree",
    name: "合欢",
    nameEn: "Silk Tree",
    country: "中国",
    region: "亚洲",
    location: { lat: 34.7466, lng: 113.6253 },
    bloomSeason: "6月-7月",
    bloomMonths: [6, 7],
    flowerColors: ["粉色"],
    emoji: "🧶",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Albizia_julibrissin4.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/合欢",
    brief: "合欢花形似绒球，粉色丝状花蕊细腻柔美，夜间叶片合拢，故有\"合欢\"\"夜合\"之名，象征夫妻恩爱和家庭和睦。",
    bloomGuide: "6-7月开放，淡粉色丝状花序如绒球，香气清淡，树冠开展，遮阴效果极佳。",
    viewingTips: "北京天坛公园、各地古典园林和道路绿化带均有种植，夏季观赏效果好。",
    category: "木本花卉"
  },
  {
    id: "chinese_bellflower",
    name: "桔梗",
    nameEn: "Chinese Bellflower",
    country: "中国",
    region: "亚洲",
    location: { lat: 43.8878, lng: 125.3245 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["蓝紫色", "白色", "粉色"],
    emoji: "🎐",
    colorHex: "#5C6BC0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/The_Botanical_Magazine,_Plate_252_(Volume_7,_1794).png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/桔梗",
    brief: "桔梗花呈钟形，蓝紫色，素雅脱俗，是中国东北朝鲜族文化中最具代表性的花卉，朝鲜族民歌《桔梗谣》广为传唱。",
    bloomGuide: "7-9月开放，花蕾气球状，开放后呈五角星形，蓝紫色花瓣纹路清晰，根部可入药食用。",
    viewingTips: "吉林延边朝鲜族自治州的山地草坡上有大片野生桔梗，是重要的观赏和民俗植物。",
    category: "草本花卉"
  },
  {
    id: "campsis",
    name: "凌霄",
    nameEn: "Campsis",
    country: "中国",
    region: "亚洲",
    location: { lat: 31.2304, lng: 121.4737 },
    bloomSeason: "6月-8月",
    bloomMonths: [6, 7, 8],
    flowerColors: ["橙色", "红色"],
    emoji: "🎺",
    colorHex: "#FF5722",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/CampsisGrandiflora.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/凌霄",
    brief: "凌霄攀援高枝，橙红色喇叭形花朵盛夏绽放，自古以凌云之志闻名，是中国传统园林中最具气势的藤本花木之一。",
    bloomGuide: "6-8月开放，橙红色喇叭形花朵，花序成簇，攀缘可达十余米，盛花时如火焰铺墙。",
    viewingTips: "苏州、杭州古典园林中常见百年老凌霄，上海豫园的凌霄花墙尤为壮观。",
    category: "木质藤本"
  },
  {
    id: "lotus_magnolia",
    name: "荷花玉兰",
    nameEn: "Southern Magnolia",
    country: "中国",
    region: "亚洲",
    location: { lat: 32.0603, lng: 118.7969 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["白色"],
    emoji: "🤍",
    colorHex: "#F5F5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/荷花玉兰-安徽合肥.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/荷花玉兰",
    brief: "荷花玉兰花朵硕大，洁白如荷，清香浓郁，是南京市花之一，南京林业大学内有众多百年古树。",
    bloomGuide: "5-7月开放，花径可达30厘米，六片厚实白色花瓣，香气醉人，树冠巨大，夏日遮阴极佳。",
    viewingTips: "南京林业大学、南京中山陵附近、武汉大学等地有著名的荷花玉兰古树群。",
    category: "木本花卉"
  },
  {
    id: "winter_jasmine",
    name: "迎春花",
    nameEn: "Winter Jasmine",
    country: "中国",
    region: "亚洲",
    location: { lat: 36.0651, lng: 103.8343 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["黄色"],
    emoji: "🔆",
    colorHex: "#FFEE58",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Jasminum_nudiflorum_kz04.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/迎春花",
    brief: "迎春花是报春使者，在冰雪未消时率先盛开，金黄色小花装点枯枝，象征春天的到来，是中国最受喜爱的早春花木之一。",
    bloomGuide: "早春1-3月先叶开放，金黄色六瓣小花密集于纤细枝条上，耐寒性强，常与梅花同期观赏。",
    viewingTips: "各地公园和庭院广泛种植，与梅花、水仙、山茶并称\"雪中四友\"，是传统春节观赏花卉。",
    category: "木本花卉"
  },
  {
    id: "lily_magnolia",
    name: "紫玉兰",
    nameEn: "Lily Magnolia",
    country: "中国",
    region: "亚洲",
    location: { lat: 30.5928, lng: 114.3055 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["紫色", "紫红色"],
    emoji: "🟪",
    colorHex: "#8E24AA",
    wikiImage: "https://pic.rmb.bdstatic.com/bjh/news/da04a191635ef0f84b33408a7756ecd9.png",
    wikiUrl: "https://zh.wikipedia.org/wiki/紫玉兰",
    brief: "紫玉兰是玉兰的近亲，花色紫红，艳丽而雅致，与白玉兰并列种植形成\"二乔玉兰\"景观，华中科技大学等地春季盛况壮观。",
    bloomGuide: "3-4月先叶开放，花朵紫红色，外紫内白，花型直立，香气较淡，但颜色极为艳丽。",
    viewingTips: "华中科技大学的紫玉兰与樱花同期盛开，春季最为美丽。",
    category: "木本花卉"
  },
  {
    id: "chinese_rose",
    name: "月季",
    nameEn: "Chinese Rose",
    country: "中国",
    region: "亚洲",
    location: { lat: 39.9042, lng: 116.4074 },
    bloomSeason: "4月-11月",
    bloomMonths: [4, 5, 6, 7, 8, 9, 10, 11],
    flowerColors: ["红色", "粉色", "黄色", "白色", "紫色"],
    emoji: "🥀",
    colorHex: "#E53935",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_chinensis.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/月季",
    brief: "月季是北京市花，有\"花中皇后\"之称，现代月季的祖先来自中国，品种超过3万种，全年反复开放，是世界上种植最广的花卉之一。",
    bloomGuide: "4月至11月持续开放，花型优美，香气浓郁，品种极为丰富，从微型月季到大花月季应有尽有。",
    viewingTips: "北京月季文化节（北京植物园）、上海植物园月季园每年春秋举办花展。",
    category: "木本花卉"
  },
  {
    id: "chinese_peony",
    name: "芍药",
    nameEn: "Chinese Peony",
    country: "中国",
    region: "亚洲",
    location: { lat: 34.7976, lng: 115.9717 },
    bloomSeason: "4月-5月",
    bloomMonths: [4, 5],
    flowerColors: ["粉色", "红色", "白色"],
    emoji: "🎗️",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lactiflora1b.UME.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/芍药",
    brief: "芍药与牡丹并称\"花中二绝\"，草本花卉之王，花朵硕大，香气袭人，扬州是中国著名的芍药花城，已有千年种植历史。",
    bloomGuide: "4-5月开放，花朵大而丰满，香气浓郁，品种繁多，花期比牡丹晚约两周，花姿妩媚动人。",
    viewingTips: "扬州瘦西湖、山东菏泽（芍药之乡）、甘肃临夏是著名的芍药观赏地。",
    category: "草本花卉"
  },
  {
    id: "sea_lavender_china",
    name: "马鞭草",
    nameEn: "Verbena",
    country: "中国",
    region: "亚洲",
    location: { lat: 31.2304, lng: 121.4737 },
    bloomSeason: "5月-10月",
    bloomMonths: [5, 6, 7, 8, 9, 10],
    flowerColors: ["紫色", "蓝紫色", "粉色", "白色"],
    emoji: "🌊",
    colorHex: "#9C27B0",
    wikiImage: "https://n.sinaimg.cn/spider20250530/436/w1700h1136/20250530/e607-e7875ffc05ac26d1640cef7a9bdabb71.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/马鞭草",
    brief: "马鞭草大面积种植时如紫色海浪，是近年中国各地花海景观中最受欢迎的花卉之一，上海、南京等地的花海吸引大量游客。",
    bloomGuide: "5-10月开放，细密的紫色小花聚集成片，微风吹过如紫色波浪涌动，特别适合大面积花海种植。",
    viewingTips: "上海鲜花港、南京江宁区、无锡拈花湾等地每年举办大规模马鞭草花海景观。",
    category: "草本花卉"
  },
  {
    id: "sophora_japonica",
    name: "国槐花",
    nameEn: "Pagoda Tree Flower",
    country: "中国",
    region: "亚洲",
    location: { lat: 39.9042, lng: 116.4074 },
    bloomSeason: "7月-8月",
    bloomMonths: [7, 8],
    flowerColors: ["白色", "淡黄色"],
    emoji: "🍯",
    colorHex: "#FFFDE7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Sophora_japonica_JPG2Aa.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/槐",
    brief: "国槐是北京的市树，夏季开放的槐花洁白清香，是北京传统饮食文化的重要组成部分，槐花饼、槐花茶深受喜爱。",
    bloomGuide: "7-8月开放，白色蝶形小花密集成串，清香弥漫，是著名的蜜源植物，城市街道夏日槐香是北京独特的城市气息。",
    viewingTips: "北京胡同古巷、各城市行道树中广泛分布，国子监街、雍和宫附近古槐最多。",
    category: "木本花卉"
  },
  {
    id: "cockscomb",
    name: "鸡冠花",
    nameEn: "Cockscomb",
    country: "中国",
    region: "亚洲",
    location: { lat: 34.3416, lng: 108.9398 },
    bloomSeason: "7月-10月",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["红色", "黄色", "橙色"],
    emoji: "🐓",
    colorHex: "#D32F2F",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Celosia_spicata.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鸡冠花",
    brief: "鸡冠花因花序形似鸡冠得名，颜色鲜艳，株型奇特，是中国传统观赏花卉，古诗词中常以其比喻忠贞高洁。",
    bloomGuide: "7-10月开放，花序扁平褶皱，形似鸡冠，颜色以深红为主，干燥后可长期保存。",
    viewingTips: "广泛种植于各地公园和庭院，陕西关中农家院落常见大片种植。",
    category: "草本花卉"
  },
  {
    id: "canna_china",
    name: "美人蕉",
    nameEn: "Canna",
    country: "中国",
    region: "亚洲",
    location: { lat: 23.1291, lng: 113.2644 },
    bloomSeason: "6月-11月",
    bloomMonths: [6, 7, 8, 9, 10, 11],
    flowerColors: ["红色", "橙色", "黄色"],
    emoji: "🔶",
    colorHex: "#FF5722",
    wikiImage: "https://pic.rmb.bdstatic.com/bjh/events/d222fba1a71765dc368bb1e6d27a5b6f3991.png@h_1280",
    wikiUrl: "https://zh.wikipedia.org/wiki/美人蕉",
    brief: "美人蕉花大色艳，叶片宽大，夏秋长期开花，是华南地区最常见的园林花卉之一，广州街道和公园中随处可见。",
    bloomGuide: "6-11月持续开放，花朵鲜艳，颜色以红、橙、黄为主，叶片宽大翠绿，植株高大，气势非凡。",
    viewingTips: "广州越秀公园、广州海珠湿地等地有大面积种植，夏季观赏效果极佳。",
    category: "球根花卉"
  },
  {
    id: "chinese_hibiscus",
    name: "朱槿",
    nameEn: "Chinese Hibiscus",
    country: "中国",
    region: "亚洲",
    location: { lat: 20.0200, lng: 110.3487 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["红色", "粉色", "橙色", "黄色"],
    emoji: "🌴",
    colorHex: "#EF5350",
    wikiImage: "https://n.sinaimg.cn/sinakd20241125s/745/w1890h1255/20241125/65cd-8ab8fbd32f53359cc7d6ff2df313b64e.png",
    wikiUrl: "https://zh.wikipedia.org/wiki/朱槿",
    brief: "朱槿是海南省省花，热带地区全年开花，花朵硕大，颜色艳丽，是热带南亚地区最常见的观赏花木之一。",
    bloomGuide: "热带地区全年开放，花朵大，单瓣或重瓣，颜色从深红到橙黄均有，每朵花只开一天，但新花不断绽放。",
    viewingTips: "海南三亚、海口等地街道和公园广泛种植，东南亚各国也是重要观赏和文化花卉。",
    category: "木本花卉"
  },
  {
    id: "tulip_netherlands",
    name: "郁金香",
    nameEn: "Tulip",
    country: "荷兰",
    region: "欧洲",
    location: { lat: 52.2660, lng: 4.5584 },
    bloomSeason: "3月-5月",
    bloomMonths: [3, 4, 5],
    flowerColors: ["红色", "黄色", "紫色", "白色", "粉色"],
    emoji: "🌷",
    colorHex: "#EF5350",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/צבעונים.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/郁金香",
    brief: "郁金香是荷兰国花，库肯霍夫公园每年春季有700万株郁金香竞相盛开，是世界上最大的鲜花公园，吸引全球游客。",
    bloomGuide: "3-5月盛开，花型优美，颜色极为丰富，单瓣、重瓣、流苏瓣等品种各有特色。",
    viewingTips: "荷兰库肯霍夫花园是世界著名的郁金香圣地，每年3-5月开放，颜色之丰富令人叹为观止。",
    category: "球根花卉"
  },
  {
    id: "poppy_france",
    name: "虞美人",
    nameEn: "Poppy",
    country: "法国",
    region: "欧洲",
    location: { lat: 43.2965, lng: 5.3698 },
    bloomSeason: "5月-6月",
    bloomMonths: [5, 6],
    flowerColors: ["红色", "橙色", "粉色", "白色"],
    emoji: "🎆",
    colorHex: "#D32F2F",
    wikiImage: "https://imgw.pconline.com.cn/images/upload/upc/tx/photoblog/1805/04/c6/spcgroup/width_600,qua_100/85679539_1525420714213.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/虞美人",
    brief: "虞美人是普罗旺斯麦田中最浪漫的野花，鲜红色花瓣薄如蝉翼，在风中飘摇，也是第一次世界大战的象征之花。",
    bloomGuide: "5-6月开放，花瓣薄而艳丽，颜色以红色为主，大片种植时如火焰海洋，微风中轻盈飘动。",
    viewingTips: "法国普罗旺斯麦田、比利时伊普尔战场是著名的虞美人观赏地，英国乡村也广泛分布。",
    category: "草本花卉"
  },
  {
    id: "heather_scotland",
    name: "石南花",
    nameEn: "Heather",
    country: "英国",
    region: "欧洲",
    location: { lat: 57.0000, lng: -4.0000 },
    bloomSeason: "8月-9月",
    bloomMonths: [8, 9],
    flowerColors: ["紫色", "粉色", "白色"],
    emoji: "💜",
    colorHex: "#AB47BC",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/CallunaVulgaris.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/帚石南",
    brief: "石南花是苏格兰高地的标志，每年8-9月将整片山丘染成紫色，是世界上最壮观的自然花海景观之一，也是苏格兰的国花。",
    bloomGuide: "8-9月盛开，灌木低矮，小花密集，整片山丘变成梦幻的紫色，是著名的摄影圣地。",
    viewingTips: "苏格兰凯恩戈姆斯国家公园、英格兰约克郡荒原是观赏石南花的最佳地点。",
    category: "木本花卉"
  },
  {
    id: "passionflower",
    name: "西番莲",
    nameEn: "Passion Flower",
    country: "巴西",
    region: "美洲",
    location: { lat: -22.9068, lng: -43.1729 },
    bloomSeason: "5月-9月",
    bloomMonths: [5, 6, 7, 8, 9],
    flowerColors: ["紫色", "蓝紫色", "白色"],
    emoji: "✝️",
    colorHex: "#7B1FA2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Passiflora_edulis_forma_flavicarpa.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/西番莲",
    brief: "西番莲原产巴西，花形奇特，放射状花丝如光环，是基督受难象征（耶稣受难花），也是百香果的花朵。",
    bloomGuide: "5-9月开放，花朵复杂精美，中央放射状紫蓝色花丝形成独特冠状结构，每朵花仅开一天。",
    viewingTips: "巴西里约热内卢植物园、圣保罗热带植物园有大量种植，也广泛分布于热带庭院中。",
    category: "草本藤本"
  },
  {
    id: "poinsettia",
    name: "一品红",
    nameEn: "Poinsettia",
    country: "墨西哥",
    region: "美洲",
    location: { lat: 19.4326, lng: -99.1332 },
    bloomSeason: "11月-1月",
    bloomMonths: [11, 12, 1],
    flowerColors: ["红色", "粉色", "白色"],
    emoji: "🎄",
    colorHex: "#C62828",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Weihnachtsstern_-_groß.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/一品红",
    brief: "一品红原产墨西哥，是全球最重要的圣诞节花卉，鲜红色苞叶如火焰般燃烧，在北半球冬季为节日增添喜庆气氛。",
    bloomGuide: "冬季11月至次年1月显色，红色部分实为苞叶而非花瓣，中央黄绿色部分才是真正的小花。",
    viewingTips: "墨西哥城市场、植物园广泛种植，全球各地花店在圣诞节前后大量销售，是节日花卉中销量第一的品种。",
    category: "木本花卉"
  },
  {
    id: "lupine_usa",
    name: "羽扇豆",
    nameEn: "Lupine",
    country: "美国",
    region: "美洲",
    location: { lat: 44.0682, lng: -114.7420 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["蓝色", "紫色", "粉色", "黄色", "白色"],
    emoji: "🌈",
    colorHex: "#5C6BC0",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lupinus_polyphyllus.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/羽扇豆",
    brief: "羽扇豆是北美西部草原的标志性花卉，穗状花序色彩缤纷，大片盛开时如彩虹落地，是冰岛和新西兰最著名的外来景观植物。",
    bloomGuide: "5-7月开放，直立花穗可达1米，颜色极为丰富，叶片如手掌张开，整体形态极为优雅。",
    viewingTips: "美国爱达荷州萨尔蒙河谷、冰岛全境、新西兰南岛是著名的羽扇豆花海观赏地。",
    category: "草本花卉"
  },
  {
    id: "amazon_lily",
    name: "亚马逊王莲",
    nameEn: "Amazon Water Lily",
    country: "巴西",
    region: "美洲",
    location: { lat: -3.4653, lng: -62.2159 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["白色", "粉色"],
    emoji: "🛟",
    colorHex: "#FCE4EC",
    wikiImage: "https://bkimg.cdn.bcebos.com/pic/9213b07eca8065380cd7e3494a88b644ad3459822469",
    wikiUrl: "https://zh.wikipedia.org/wiki/亚马逊王莲",
    brief: "亚马逊王莲是世界上最大的浮叶植物，叶片直径可达3米，可承重数十公斤，白色花朵第一天开放，次日变为粉红，是亚马逊雨林最神奇的花卉。",
    bloomGuide: "热带地区全年可开放，花朵夜间开放，散发强烈香气，第一天白色，第二天变粉，依赖金龟子授粉。",
    viewingTips: "巴西亚马逊河流域、中国各大热带植物园温室水池中有引种栽培，是著名的观赏水生植物。",
    category: "水生花卉"
  },
  {
    id: "strelitzia_reginae",
    name: "鹤望兰",
    nameEn: "Bird of Paradise",
    country: "南非",
    region: "非洲",
    location: { lat: -26.2041, lng: 28.0473 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["橙色", "蓝色"],
    emoji: "🦩",
    colorHex: "#FF8F00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bird_of_Paradise_flower.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鹤望兰",
    brief: "鹤望兰（天堂鸟）原产南非，橙蓝两色的奇特花形宛如飞翔的鸟儿，是南非重要的出口花卉，也是洛杉矶市花。",
    bloomGuide: "热带和亚热带地区全年可开放，花朵奇特，橙色花萼如鸟冠，蓝色花瓣如翅膀，单株花期长达数周。",
    viewingTips: "南非开普敦植物园、约翰内斯堡植物园有大量野生鹤望兰，也可在世界各地花卉市场见到切花。",
    category: "草本花卉"
  },
  {
    id: "candelabra_aloe",
    name: "芦荟花",
    nameEn: "Aloe Flower",
    country: "南非",
    region: "非洲",
    location: { lat: -29.0852, lng: 26.1596 },
    bloomSeason: "6月-8月",
    bloomMonths: [6, 7, 8],
    flowerColors: ["橙色", "红色", "黄色"],
    emoji: "🕯️",
    colorHex: "#FF6D00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Aloe_vera_flower_inset.png?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/芦荟",
    brief: "南非苦芦荟在南半球冬季盛开橙红色高大花穗，是非洲荒野中最壮观的多肉植物花卉，山坡上密集开放时景色震撼。",
    bloomGuide: "南半球冬季6-8月开放，高大的花穗橙红色，可高达1米，是鸟类和昆虫的重要蜜源。",
    viewingTips: "南非开普省山地、纳马夸兰地区是观赏野生芦荟花海的最佳地点，每年冬季花朵密集盛开。",
    category: "多肉植物"
  },
  {
    id: "namaqualand_daisy",
    name: "纳马夸兰雏菊",
    nameEn: "Namaqualand Daisy",
    country: "南非",
    region: "非洲",
    location: { lat: -29.5765, lng: 17.6571 },
    bloomSeason: "8月-9月",
    bloomMonths: [8, 9],
    flowerColors: ["橙色", "黄色", "白色"],
    emoji: "🧿",
    colorHex: "#FF9800",
    wikiImage: "https://bkimg.cdn.bcebos.com/pic/dc54564e9258d109ac321c23d758ccbf6d814d49",
    wikiUrl: "https://zh.wikipedia.org/wiki/纳马夸兰",
    brief: "纳马夸兰是南非的沙漠地区，每年8-9月雨后橙黄色野花铺满大地，被称为世界七大花海奇观之一，吸引全球游客朝圣。",
    bloomGuide: "南半球冬末春初的8-9月雨后开放，橙黄色雏菊密铺地面，一望无际，是自然界最壮观的花海景象之一。",
    viewingTips: "南非西开普省纳马夸兰国家公园、斯普林博克地区是观赏花海的最佳地点，需要在雨后一周内前往。",
    category: "草本花卉"
  },
  {
    id: "wattle_australia",
    name: "金合欢",
    nameEn: "Golden Wattle",
    country: "澳大利亚",
    region: "大洋洲",
    location: { lat: -35.2809, lng: 149.1300 },
    bloomSeason: "8月-9月",
    bloomMonths: [8, 9],
    flowerColors: ["金黄色", "黄色"],
    emoji: "☀️",
    colorHex: "#F9A825",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Acacia_pycnantha_Golden_Wattle.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/金合欢",
    brief: "金合欢是澳大利亚国花，每年8-9月金黄色小花球密密麻麻覆盖树冠，澳大利亚国徽上就有金合欢的图案，是国家认同的重要象征。",
    bloomGuide: "南半球冬末春初的8-9月盛开，细密的金黄色球状花序芳香四溢，是澳大利亚最标志性的春花。",
    viewingTips: "澳大利亚首都堪培拉周边灌木丛、悉尼蓝山地区是观赏野生金合欢的好地方，9月1日是澳大利亚国家金合欢日。",
    category: "木本花卉"
  },
  {
    id: "pohutukawa",
    name: "圣诞树花",
    nameEn: "Pohutukawa",
    country: "新西兰",
    region: "大洋洲",
    location: { lat: -36.8485, lng: 174.7633 },
    bloomSeason: "11月-1月",
    bloomMonths: [11, 12, 1],
    flowerColors: ["红色", "深红色"],
    emoji: "🎅",
    colorHex: "#B71C1C",
    wikiImage: "https://img.pconline.com.cn/images/upload/upc/tx/photoblog/1812/17/c5/124090930_1545015704819_mthumb.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/圣诞树",
    brief: "圣诞树花（波胡图卡瓦）是新西兰的原生树木，每年夏季（南半球12月圣诞节前后）盛开鲜红色花朵，是新西兰标志性的圣诞花卉。",
    bloomGuide: "南半球夏季11月-1月开放，深红色花丝构成绒球状花序，开花时整棵树变成红色，壮观无比。",
    viewingTips: "新西兰奥克兰海滨、科罗曼德尔半岛的海岸线上有大量野生圣诞树，夏季海滨落花如红毯。",
    category: "木本花卉"
  },
  {
    id: "ylang_ylang",
    name: "依兰花",
    nameEn: "Ylang Ylang",
    country: "菲律宾",
    region: "亚洲",
    location: { lat: 10.3157, lng: 123.8854 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["黄色", "金黄色"],
    emoji: "🧴",
    colorHex: "#F9A825",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cananga_odorata_01.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/依兰",
    brief: "依兰花香气浓烈迷人，是著名的香水原料，提取的依兰精油是香奈儿5号香水的主要成分之一，在东南亚是婚礼和节日的圣洁花卉。",
    bloomGuide: "热带地区全年开放，黄色花朵细长下垂，香气馥郁，一棵成年树每年可产数十公斤花朵用于提炼精油。",
    viewingTips: "菲律宾宿雾、科摩罗群岛是依兰花的主要产地，东南亚各地花市也常见这种芳香花卉。",
    category: "木本花卉"
  },
  {
    id: "chinese_lantern_fuchsia",
    name: "倒挂金钟",
    nameEn: "Fuchsia",
    country: "中国",
    region: "亚洲",
    location: { lat: 29.5630, lng: 106.5516 },
    bloomSeason: "4月-11月",
    bloomMonths: [4, 5, 6, 7, 8, 9, 10, 11],
    flowerColors: ["红色", "紫色", "粉色"],
    emoji: "🪅",
    colorHex: "#C62828",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Fuchsia_magellanica.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/倒挂金钟",
    brief: "倒挂金钟花如悬挂的小灯笼，颜色鲜艳，花期极长，重庆城区花圃广泛种植，是西南地区著名的观赏花卉。",
    bloomGuide: "花朵悬挂下垂，外层萼片张开，内层花瓣伸出，形似倒挂灯笼，极为可爱，喜凉爽环境。",
    viewingTips: "重庆南山植物园、成都温室花圃是观赏倒挂金钟的好地方，也可作室内盆栽。",
    category: "草本花卉"
  },
  {
    id: "chinese_snowball",
    name: "绣球",
    nameEn: "Hydrangea",
    country: "中国",
    region: "亚洲",
    location: { lat: 28.2000, lng: 112.9700 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["蓝色", "粉色", "紫色", "白色"],
    emoji: "💎",
    colorHex: "#42A5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/紫色繡球花.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/绣球花",
    brief: "绣球花是近年中国最流行的庭院花卉，大型球状花序颜色会随土壤酸碱度变化，酸性土壤呈蓝色，碱性呈粉色，是\"变色花\"的代表。",
    bloomGuide: "5-7月开放，花序球形硕大，颜色随土壤pH变化，蓝色、紫色、粉色均可，花期持久，也适合做干花。",
    viewingTips: "浙江金华绣球花节、上海植物园绣球展、江苏常熟沙家浜是著名的赏绣球花地点。",
    category: "木本花卉"
  },
  {
    id: "chinese_pear_peach",
    name: "碧桃",
    nameEn: "Ornamental Peach",
    country: "中国",
    region: "亚洲",
    location: { lat: 34.2667, lng: 108.9333 },
    bloomSeason: "3月-4月",
    bloomMonths: [3, 4],
    flowerColors: ["粉色", "深粉色", "白色", "红色"],
    emoji: "🌳",
    colorHex: "#F48FB1",
    wikiImage: "https://n.sinaimg.cn/sinakd10113/213/w2048h1365/20230426/f34d-8e8a2fc94fb50173eba0d5e14967d442.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/桃花",
    brief: "碧桃是桃树的观赏品种，重瓣花型丰满，花期恰逢清明节，与柳树共同构成中国春天最经典的景致，陕西西安灞桥十里春风最为著名。",
    bloomGuide: "3-4月与杏花、李花同期盛开，重瓣花朵丰满艳丽，枝条柔美，与垂柳搭配形成中国春季最美画面。",
    viewingTips: "西安灞柳风情区、北京玉渊潭公园、南京石象路是著名的碧桃观赏地，清明节前后最为壮观。",
    category: "木本花卉"
  },
  {
    id: "crocus",
    name: "番红花",
    nameEn: "Crocus",
    country: "荷兰",
    region: "欧洲",
    location: { lat: 52.3676, lng: 4.9041 },
    bloomSeason: "2月-3月",
    bloomMonths: [2, 3],
    flowerColors: ["紫色", "白色", "黄色"],
    emoji: "🫐",
    colorHex: "#7B1FA2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/860808-Saffronfarm-01-IMG_7707-2.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/番红花",
    brief: "番红花是欧洲最早报春的花卉之一，同时也是名贵香料藏红花的来源。荷兰与伊朗是主要种植区。",
    bloomGuide: "早春2-3月在雪融之际率先绽放，紫色、白色、黄色小花在草地上成片盛开，为冬末带来第一抹色彩。",
    viewingTips: "荷兰库肯霍夫公园、英国皇家植物园邱园均有大规模种植，早春最佳。",
    category: "球根花卉"
  },
  {
    id: "lily_of_valley",
    name: "铃兰",
    nameEn: "Lily of the Valley",
    country: "法国",
    region: "欧洲",
    location: { lat: 48.8566, lng: 2.3522 },
    bloomSeason: "4月-5月",
    bloomMonths: [4, 5],
    flowerColors: ["白色"],
    emoji: "🍀",
    colorHex: "#F5F5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Convallaria_majalis_inflorescence_-_Keila.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/铃兰",
    brief: "铃兰是法国五月一日劳动节的象征花卉，法国人在这一天互赠铃兰表达美好祝愿，被誉为幸福之花。",
    bloomGuide: "4-5月开放，钟形白色小花串珠般挂于茎上，清香淡雅，叶片宽大翠绿，极具观赏价值。",
    viewingTips: "法国巴黎花市在五月初大量供应铃兰，芬兰和瑞典的森林中也有大量野生分布。",
    category: "草本花卉"
  },
  {
    id: "cornflower",
    name: "矢车菊",
    nameEn: "Cornflower",
    country: "德国",
    region: "欧洲",
    location: { lat: 52.5200, lng: 13.4050 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["蓝色", "紫色", "粉色", "白色"],
    emoji: "🔵",
    colorHex: "#1976D2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Centaurea_cyanus_flower_001.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/矢车菊",
    brief: "矢车菊是德国国花，象征幸福与优雅。蓝色矢车菊曾是普鲁士威廉一世最喜爱的花卉。",
    bloomGuide: "5-7月盛开，花朵精致如放射状的星芒，蓝色最为经典，在麦田和草地边大片盛开。",
    viewingTips: "德国巴伐利亚乡村麦田、法国普罗旺斯田间均可见到蓝色矢车菊与红色虞美人交织的美景。",
    category: "草本花卉"
  },
  {
    id: "gladiolus",
    name: "唐菖蒲",
    nameEn: "Gladiolus",
    country: "荷兰",
    region: "欧洲",
    location: { lat: 52.1326, lng: 5.2913 },
    bloomSeason: "6月-9月",
    bloomMonths: [6, 7, 8, 9],
    flowerColors: ["红色", "粉色", "白色", "黄色", "紫色", "橙色"],
    emoji: "⚔️",
    colorHex: "#E53935",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/0_Gladiolus_italicus_-_Samoëns_(1).JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/唐菖蒲",
    brief: "唐菖蒲又称剑兰，因叶片形似宝剑得名。是世界四大切花之一，荷兰是全球最大的产地和出口国。",
    bloomGuide: "夏季6-9月开放，穗状花序高大挺拔，花朵从下往上依次开放，颜色极为丰富，可达1.5米高。",
    viewingTips: "荷兰花卉拍卖市场、各大花展中大量展出，是婚礼和庆典的常用花材。",
    category: "球根花卉"
  },
  {
    id: "mimosa",
    name: "含羞草花",
    nameEn: "Mimosa",
    country: "法国",
    region: "欧洲",
    location: { lat: 43.5513, lng: 6.9260 },
    bloomSeason: "1月-3月",
    bloomMonths: [1, 2, 3],
    flowerColors: ["黄色"],
    emoji: "✳️",
    colorHex: "#FFD600",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Acacia_dealbata-1.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/银荆",
    brief: "法国蔚蓝海岸的含羞草在冬末金黄绽放，每年2月芒德略至格拉斯之间举办著名的含羞草节，花车巡游热闹非凡。",
    bloomGuide: "1-3月盛开，细密的金黄色球形花序散发甜蜜香气，整棵树犹如一团金色云朵。",
    viewingTips: "法国格拉斯至芒德略的含羞草之路是著名的冬季花卉观赏线路，2月含羞草节是法国里维埃拉的盛事。",
    category: "木本花卉"
  },
  {
    id: "orchid_vanilla",
    name: "香草兰",
    nameEn: "Vanilla Orchid",
    country: "墨西哥",
    region: "美洲",
    location: { lat: 20.2116, lng: -96.8716 },
    bloomSeason: "3月-5月",
    bloomMonths: [3, 4, 5],
    flowerColors: ["黄色", "淡绿色"],
    emoji: "🍦",
    colorHex: "#C8E6C9",
    wikiImage: "https://qcloud.dpfile.com/pc/GNAclAeFYZp-LFYfR1TDTIW53cMa6wCrIRotxccmURws-NirLunxqSrq2ypWZ3UE.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/香草兰",
    brief: "香草兰是香草冰淇淋和糕点中天然香草的来源，原产墨西哥，是世界上最珍贵的兰花之一。",
    bloomGuide: "3-5月开花，淡黄绿色花朵仅开一天，需人工授粉才能结出香草荚果，栽培难度极高。",
    viewingTips: "墨西哥韦拉克鲁斯州是香草兰原产地，马达加斯加和塔希提也大量种植。",
    category: "草本藤本"
  },
  {
    id: "frangipani_hawaii",
    name: "火焰树花",
    nameEn: "Royal Poinciana",
    country: "巴西",
    region: "美洲",
    location: { lat: -12.9714, lng: -38.5124 },
    bloomSeason: "10月-2月",
    bloomMonths: [10, 11, 12, 1, 2],
    flowerColors: ["红色", "橙色"],
    emoji: "🌺",
    colorHex: "#E64A19",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Royal_Poinciana.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/凤凰木",
    brief: "火焰树（凤凰木）被誉为世界上最美丽的热带观花树种，盛花时全树一片火红，如烈焰燃烧，是热带城市的标志性景观。",
    bloomGuide: "南半球夏季10月至次年2月盛开，红色蝶形花朵密集覆盖树冠，远看如一团燃烧的火焰。",
    viewingTips: "中国深圳、巴西萨尔瓦多、澳大利亚达尔文均有大量凤凰木，夏季开花极为壮观。",
    category: "木本花卉"
  },
  {
    id: "fuchsia_chile",
    name: "智利国花",
    nameEn: "Chilean Bellflower",
    country: "智利",
    region: "美洲",
    location: { lat: -38.7399, lng: -72.5901 },
    bloomSeason: "12月-3月",
    bloomMonths: [12, 1, 2, 3],
    flowerColors: ["红色", "粉色", "白色"],
    emoji: "🛎️",
    colorHex: "#D32F2F",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lapageria_rosea_Strybing.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/智利铃花",
    brief: "智利铃花（Copihue）是智利国花，钟形花朵如红色宝石悬挂在森林中，生长在温带雨林，象征着智利民族的坚韧与美丽。",
    bloomGuide: "南半球夏季12月至次年3月开放，蜡质钟形花朵红色或粉色，悬垂于藤蔓上，花期持久。",
    viewingTips: "智利阿劳卡尼亚大区的温带雨林是观赏野生智利铃花的最佳地点，受法律保护。",
    category: "木质藤本"
  },
  {
    id: "angel_trumpet",
    name: "曼陀罗",
    nameEn: "Angel's Trumpet",
    country: "秘鲁",
    region: "美洲",
    location: { lat: -13.5320, lng: -71.9675 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["白色", "粉色", "黄色", "橙色"],
    emoji: "📣",
    colorHex: "#FFF9C4",
    wikiImage: "https://i2.hdslb.com/bfs/archive/3f71dcbf68ff30fa470a6d2c420750ec84ec7bc7.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/曼陀罗属",
    brief: "曼陀罗花形如天使的喇叭，大型下垂花朵散发迷人香气。原产南美安第斯山脉，在印加文化中有重要地位。",
    bloomGuide: "热带地区全年可开花，喇叭形花朵下垂，长可达30厘米，夜间香气最为浓烈，极具异域风情。",
    viewingTips: "秘鲁库斯科、厄瓜多尔基多的庭院和公园中广泛种植，是安第斯地区最具特色的花卉。",
    category: "木本花卉"
  },
  {
    id: "chocolate_cosmos",
    name: "巧克力秋英",
    nameEn: "Chocolate Cosmos",
    country: "墨西哥",
    region: "美洲",
    location: { lat: 19.7026, lng: -99.2088 },
    bloomSeason: "7月-10月",
    bloomMonths: [7, 8, 9, 10],
    flowerColors: ["红色", "棕红色"],
    emoji: "🍫",
    colorHex: "#4E342E",
    wikiImage: "https://pics0.baidu.com/feed/d1a20cf431adcbef19b0aa684a3413cda2cc9f00.png@f_auto?token=37ec9f6d2a4d1ddfa2ec71885a572dfa",
    wikiUrl: "https://zh.wikipedia.org/wiki/巧克力秋英",
    brief: "巧克力秋英是世界上唯一散发巧克力香气的花卉，暗红色如天鹅绒般的花瓣极具魅力，野生种已濒临灭绝。",
    bloomGuide: "夏秋7-10月开放，深红褐色花朵直径约4厘米，散发浓郁的巧克力和香草混合香气。",
    viewingTips: "墨西哥城附近植物园有保育种植，全球各大植物园温室中也有展出，属珍稀观赏花卉。",
    category: "球根花卉"
  },
  {
    id: "african_violet",
    name: "非洲紫罗兰",
    nameEn: "African Violet",
    country: "坦桑尼亚",
    region: "非洲",
    location: { lat: -5.0893, lng: 38.3229 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["紫色", "粉色", "白色", "蓝色"],
    emoji: "🔮",
    colorHex: "#7E57C2",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Saintpaulia_ionantha.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/非洲紫罗兰",
    brief: "非洲紫罗兰原产坦桑尼亚乌桑巴拉山区，是世界上最受欢迎的室内盆栽花卉，品种超过16000个。",
    bloomGuide: "室内环境下全年可开花，紫色、粉色、蓝色等花色丰富，花朵精致可爱，叶片肥厚毛茸。",
    viewingTips: "坦桑尼亚乌桑巴拉山脉是其原产地，各国花卉展均有大量品种展出。",
    category: "草本花卉"
  },
  {
    id: "desert_rose",
    name: "沙漠玫瑰",
    nameEn: "Desert Rose",
    country: "肯尼亚",
    region: "非洲",
    location: { lat: 0.0236, lng: 37.9062 },
    bloomSeason: "4月-9月",
    bloomMonths: [4, 5, 6, 7, 8, 9],
    flowerColors: ["粉色", "红色", "白色"],
    emoji: "🏜️",
    colorHex: "#EC407A",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/沙漠玫瑰",
    brief: "沙漠玫瑰以膨大的瓶状树干和艳丽的粉红色花朵闻名，原产东非干旱地区，是最具异域风情的多肉花卉。",
    bloomGuide: "旱季结束后4-9月大量开花，粉红色喇叭形花朵聚生枝头，与粗壮的瓶状树干形成鲜明对比。",
    viewingTips: "肯尼亚、索科特拉岛可见野生沙漠玫瑰，全球热带地区广泛栽培为观赏盆栽。",
    category: "多肉植物"
  },
  {
    id: "flame_lily",
    name: "火焰百合",
    nameEn: "Flame Lily",
    country: "津巴布韦",
    region: "非洲",
    location: { lat: -17.8252, lng: 31.0335 },
    bloomSeason: "11月-3月",
    bloomMonths: [11, 12, 1, 2, 3],
    flowerColors: ["红色", "黄色", "橙色"],
    emoji: "💥",
    colorHex: "#FF5722",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Flame_Lily.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/嘉兰",
    brief: "火焰百合是津巴布韦国花，花瓣向后卷曲如跳动的火焰，红黄渐变色彩极为惊艳，是非洲最美丽的野生花卉之一。",
    bloomGuide: "雨季11月至次年3月开放，花瓣向后翻卷，边缘波浪形，从黄色渐变为鲜红，宛如火焰跳动。",
    viewingTips: "津巴布韦维多利亚瀑布附近的灌木丛中可见野生火焰百合，也是赞比亚和坦桑尼亚的标志花卉。",
    category: "球根花卉"
  },
  {
    id: "plumbago",
    name: "蓝雪花",
    nameEn: "Plumbago",
    country: "南非",
    region: "非洲",
    location: { lat: -33.9249, lng: 18.4241 },
    bloomSeason: "9月-4月",
    bloomMonths: [9, 10, 11, 12, 1, 2, 3, 4],
    flowerColors: ["蓝色", "白色"],
    emoji: "🧊",
    colorHex: "#42A5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Plumbago.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/蓝雪花",
    brief: "蓝雪花原产南非，天蓝色花朵密集成球，是热带和亚热带地区最受欢迎的庭院花卉之一，常被用作花篱。",
    bloomGuide: "花期长达半年以上，天蓝色五瓣小花聚集成球状花序，在阳光下呈现梦幻的冰蓝色调。",
    viewingTips: "南非开普敦各处庭院广泛种植，中国南方和东南亚地区也作为庭院花卉栽培。",
    category: "木本花卉"
  },
  {
    id: "fynbos_erica",
    name: "石楠花",
    nameEn: "Cape Erica",
    country: "南非",
    region: "非洲",
    location: { lat: -34.0522, lng: 18.4737 },
    bloomSeason: "6月-10月",
    bloomMonths: [6, 7, 8, 9, 10],
    flowerColors: ["粉色", "红色", "白色"],
    emoji: "🩶",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Amrum_(187753235).jpeg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/欧石楠属",
    brief: "南非开普地区拥有超过700种石楠花，是全球石楠花种类最丰富的地方，密集的粉色和白色小花构成独特的芬博斯植被景观。",
    bloomGuide: "南半球冬春6-10月盛开，管状或钟形小花密集排列，颜色从白到深红各异，常与帝王花共生。",
    viewingTips: "南非开普花卉保护区、桌山国家公园是观赏芬博斯石楠花群落的最佳地点。",
    category: "木本花卉"
  },

  // --- 大洋洲 3 种 ---
  {
    id: "kowhai",
    name: "科怀花",
    nameEn: "Kowhai",
    country: "新西兰",
    region: "大洋洲",
    location: { lat: -41.2866, lng: 174.7756 },
    bloomSeason: "9月-11月",
    bloomMonths: [9, 10, 11],
    flowerColors: ["黄色"],
    emoji: "🐦",
    colorHex: "#FFD600",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Kowhai_in_full_bloom_at_Papakowhai_School.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/黄槐属",
    brief: "科怀花是新西兰非官方国花，金黄色的钟形花朵是新西兰春天的标志，也是新西兰蜜雀鸟最喜爱的蜜源。",
    bloomGuide: "南半球春季9-11月盛开，垂挂的金黄色蝶形花朵吸引大量蜜雀前来采蜜，形成花鸟共生的美景。",
    viewingTips: "新西兰惠灵顿植物园、奥克兰各地公园均有种植，春季在全国各地均可见到。",
    category: "木本花卉"
  },
  {
    id: "banksia",
    name: "班克木花",
    nameEn: "Banksia",
    country: "澳大利亚",
    region: "大洋洲",
    location: { lat: -31.9505, lng: 115.8605 },
    bloomSeason: "3月-8月",
    bloomMonths: [3, 4, 5, 6, 7, 8],
    flowerColors: ["黄色", "橙色", "红色"],
    emoji: "🌼",
    colorHex: "#FF8F00",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Banksia_in_the_Blue_Mountains.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/班克木属",
    brief: "班克木花是澳大利亚独有的原生花卉，圆柱形花穗由数千朵小花密集排列而成，造型奇特如火炬，是澳洲特有的灌木林景观。",
    bloomGuide: "秋冬3-8月开放，花穗高达30厘米，颜色从黄色到红色渐变，果实开裂后如张着大嘴的面具。",
    viewingTips: "西澳大利亚的金花之路是观赏班克木花的绝佳路线，悉尼皇家植物园也有收藏。",
    category: "木本花卉"
  },
  {
    id: "christmas_bush",
    name: "圣诞灌木花",
    nameEn: "New South Wales Christmas Bush",
    country: "澳大利亚",
    region: "大洋洲",
    location: { lat: -33.8688, lng: 151.2093 },
    bloomSeason: "11月-1月",
    bloomMonths: [11, 12, 1],
    flowerColors: ["红色", "粉色"],
    emoji: "🎁",
    colorHex: "#C62828",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Ceratopetalum_gummiferum_Garigal.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/圣诞灌木",
    brief: "圣诞灌木花是澳大利亚新南威尔士州的圣诞象征，每年12月花萼变为鲜红色，在南半球炎热的圣诞节替代北方的一品红。",
    bloomGuide: "南半球夏季11月至次年1月，白色小花凋谢后花萼逐渐变红，整株灌木变成喜庆的红色。",
    viewingTips: "悉尼皇家植物园、蓝山地区在圣诞前后可见到大量开花的圣诞灌木。",
    category: "木本花卉"
  },
  {
    id: "frangipani",
    name: "素馨花",
    nameEn: "Frangipani",
    country: "印度尼西亚",
    region: "亚洲",
    location: { lat: -8.3405, lng: 115.0920 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["白色", "黄色", "粉色"],
    emoji: "🕉️",
    colorHex: "#FFF9C4",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Plumeria_rubra-4.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/鸡蛋花属",
    brief: "素馨花是巴厘岛文化的重要象征，洁白的花朵广泛用于印度教寺庙供花和传统SPA水疗。花香清甜迷人。",
    bloomGuide: "热带地区全年开花，花朵白色带黄心，五片花瓣旋转排列如风车，散发浓郁甜美香气。",
    viewingTips: "印度尼西亚巴厘岛的寺庙和度假村随处可见，是东南亚最具代表性的热带花卉之一。",
    category: "木本花卉"
  },
  {
    id: "osmanthus_tea",
    name: "栀子花",
    nameEn: "Gardenia",
    country: "中国",
    region: "亚洲",
    location: { lat: 28.2278, lng: 112.9388 },
    bloomSeason: "5月-7月",
    bloomMonths: [5, 6, 7],
    flowerColors: ["白色"],
    emoji: "🧈",
    colorHex: "#FFFDE7",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Gardenia_jasminoides_flower_Argentina.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/栀子花",
    brief: "栀子花是中国南方夏季最具代表性的芳香花卉，洁白如玉的花朵散发浓郁甜香。\"栀子花开\"是许多中国人关于夏天的青春记忆。",
    bloomGuide: "5-7月开放，重瓣白色花朵如玉雕般精致，香气浓郁甜美，可持续数日。",
    viewingTips: "中国南方各地庭院广泛种植，湖南、江西、浙江农村家家户户门前常见。",
    category: "木本花卉"
  },
  {
    id: "lotus_vietnam",
    name: "越南莲花",
    nameEn: "Vietnamese Lotus",
    country: "越南",
    region: "亚洲",
    location: { lat: 21.0278, lng: 105.8342 },
    bloomSeason: "5月-8月",
    bloomMonths: [5, 6, 7, 8],
    flowerColors: ["粉色", "白色"],
    emoji: "🪺",
    colorHex: "#F48FB1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Fleur_de_lotus.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/莲",
    brief: "莲花是越南国花，在越南文化中象征着纯洁与坚韧。河内西湖的莲花池是越南最著名的赏莲景观。",
    bloomGuide: "夏季5-8月盛开，粉色花朵在碧绿荷叶间亭亭玉立，清晨6-8点花朵最为饱满鲜艳。",
    viewingTips: "河内西湖、顺化皇宫护城河是越南最著名的赏莲地点，夏季清晨最佳。",
    category: "水生花卉"
  },
  {
    id: "mangosteen_flower",
    name: "缅栀花",
    nameEn: "Dok Champa",
    country: "老挝",
    region: "亚洲",
    location: { lat: 17.9757, lng: 102.6331 },
    bloomSeason: "4月-9月",
    bloomMonths: [4, 5, 6, 7, 8, 9],
    flowerColors: ["白色", "黄色", "粉色"],
    emoji: "☸️",
    colorHex: "#FFF9C4",
    wikiImage: "https://photo.tuchong.com/13290193/f/796002151.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/鸡蛋花",
    brief: "缅栀花（占芭花）是老挝国花，洁白芳香，象征纯洁与快乐。在老挝传统节日和宗教仪式中不可或缺。",
    bloomGuide: "4-9月开放，五瓣白色花朵中心淡黄，花香淡雅持久，是东南亚寺庙常见的供花。",
    viewingTips: "老挝琅勃拉邦、万象的寺庙和街道上大量种植，泼水节期间是观赏占芭花的最佳时机。",
    category: "木本花卉"
  },
  {
    id: "spider_lily",
    name: "彼岸花",
    nameEn: "Red Spider Lily",
    country: "日本",
    region: "亚洲",
    location: { lat: 35.8592, lng: 139.6450 },
    bloomSeason: "9月-10月",
    bloomMonths: [9, 10],
    flowerColors: ["红色", "白色"],
    emoji: "🌺",
    colorHex: "#D32F2F",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cluster_amaryllis_close-up.jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/石蒜",
    brief: "彼岸花在日本秋分前后盛开，被视为接引之花。鲜红色花朵花叶永不相见，充满神秘色彩，是日本文学和动漫中的经典意象。",
    bloomGuide: "秋季9-10月开放，鲜红色花瓣向后卷曲，花蕊细长突出，花谢后叶片才长出，花叶永不相见。",
    viewingTips: "日本埼�的�的权现堂堤有500万株彼岸花田，秋分时节一片血红色花海极为壮观。",
    category: "球根花卉"
  },
  {
    id: "gardenia_cape",
    name: "夜来香",
    nameEn: "Tuberose",
    country: "印度",
    region: "亚洲",
    location: { lat: 12.9716, lng: 77.5946 },
    bloomSeason: "7月-11月",
    bloomMonths: [7, 8, 9, 10, 11],
    flowerColors: ["白色"],
    emoji: "🌃",
    colorHex: "#F5F5F5",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cestrum_nocturnum_(2464189820).jpg?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/夜来香",
    brief: "夜来香是世界最著名的夜间芳香花卉，白色花朵在夜间散发浓郁迷人的甜香。印度是全球最大的夜来香产地。",
    bloomGuide: "夏秋7-11月开放，白色管状花朵串生于花茎上，入夜后香气浓烈，是重要的香水和宗教用花。",
    viewingTips: "印度班加罗尔、泰国曼谷花市夜间可闻到浓郁的夜来香香气，是南亚婚礼的必备花卉。",
    category: "球根花卉"
  },
  {
    id: "chamomile_russia",
    name: "甘菊",
    nameEn: "Chamomile",
    country: "俄罗斯",
    region: "欧洲",
    location: { lat: 55.7558, lng: 37.6173 },
    bloomSeason: "6月-8月",
    bloomMonths: [6, 7, 8],
    flowerColors: ["白色", "黄色"],
    emoji: "🌼",
    colorHex: "#FFF9C4",
    wikiImage: "https://bkimg.cdn.bcebos.com/pic/d53f8794a4c27d1eb8d6541e15d5ad6edcc43873",
    wikiUrl: "https://zh.wikipedia.org/wiki/母菊",
    brief: "甘菊是俄罗斯的非官方国花，白色花瓣配金黄色花心是俄罗斯田野最标志性的夏日风景。在俄罗斯文化中象征纯洁与爱情，姑娘们用甘菊编织花冠庆祝伊万·库帕拉节。",
    bloomGuide: "6-8月盛开，白色舌状花瓣围绕黄色管状花心，成片盛开时如白色花海铺满原野，散发淡淡苹果清香。",
    viewingTips: "莫斯科近郊的草原和田野、伏尔加河畔的乡村在夏季可见大片甘菊花海，是俄罗斯夏天最浪漫的景致。",
    category: "草本花卉"
  },
  {
    id: "tulip_kazakhstan",
    name: "哈萨克野郁金香",
    nameEn: "Greig's Tulip",
    country: "哈萨克斯坦",
    region: "亚洲",
    location: { lat: 43.2220, lng: 76.8512 },
    bloomSeason: "3月-5月",
    bloomMonths: [3, 4, 5],
    flowerColors: ["红色", "黄色", "橙色"],
    emoji: "🌷",
    colorHex: "#E53935",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/צבעונים.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/郁金香属",
    brief: "哈萨克斯坦是郁金香的原产地之一，格里格郁金香以鲜红花瓣和独特的条纹叶片闻名。天山山脉脚下的草原是世界野生郁金香多样性最高的地区。",
    bloomGuide: "3-5月在草原上大片盛开，花朵比栽培品种小但色彩更为艳丽，常与积雪未融的天山雪峰交相辉映。",
    viewingTips: "哈萨克斯坦阿拉木图近郊的阿克苏-扎巴格雷自然保护区是观赏野生郁金香的圣地。",
    category: "球根花卉"
  },
  {
    id: "cotton_flower_uzbekistan",
    name: "棉花",
    nameEn: "Cotton Flower",
    country: "乌兹别克斯坦",
    region: "亚洲",
    location: { lat: 41.2995, lng: 69.2401 },
    bloomSeason: "7月-9月",
    bloomMonths: [7, 8, 9],
    flowerColors: ["白色", "黄色", "粉色"],
    emoji: "☁️",
    colorHex: "#FFF8E1",
    wikiImage: "https://commons.wikimedia.org/wiki/Special:FilePath/CottonPlant.JPG?width=640",
    wikiUrl: "https://zh.wikipedia.org/wiki/棉花",
    brief: "棉花是乌兹别克斯坦的国花和经济命脉，被称为'白色黄金'。棉花的花朵从乳白色渐变为粉红色，花落后结出洁白的棉絮，是中亚最具代表性的农业花卉。",
    bloomGuide: "7-9月开花，花朵清晨乳白色，傍晚变为粉红色，一朵花仅开放一天，之后结出棉铃，成熟时爆裂露出白色棉絮。",
    viewingTips: "乌兹别克斯坦费尔干纳谷地、布哈拉周边的棉田在秋季收获时一片白色，是中亚最壮观的农业景观。",
    category: "草本花卉"
  },
  {
    id: "flame_tree_nigeria",
    name: "火焰花",
    nameEn: "African Tulip Tree",
    country: "尼日利亚",
    region: "非洲",
    location: { lat: 9.0579, lng: 7.4951 },
    bloomSeason: "全年",
    bloomMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    flowerColors: ["红色", "橙色"],
    emoji: "🔥",
    colorHex: "#FF3D00",
    wikiImage: "https://sns-img-hw.xhscdn.com/1000g0081tc5m3emeq0005nfkrppg9edbm13e6ho?imageView2/2/h/1080/format/webp",
    wikiUrl: "https://zh.wikipedia.org/wiki/火焰树",
    brief: "非洲火焰花（郁金香树）是西非热带地区最壮观的开花乔木，巨大的橙红色钟形花朵成簇生于树冠顶端，远望如烈焰燃烧，是尼日利亚城市绿化的标志性树种。",
    bloomGuide: "热带气候下几乎全年开花，花蕾含水，花朵鲜红硕大，花瓣边缘带金黄色镶边，树冠开花时极为壮观。",
    viewingTips: "尼日利亚阿布贾、拉各斯的城市街道和公园广泛种植，加纳阿克拉、喀麦隆也常见。",
    category: "木本花卉"
  },
  {
    id: "baobab_flower_senegal",
    name: "猴面包树花",
    nameEn: "Baobab Flower",
    country: "塞内加尔",
    region: "非洲",
    location: { lat: 14.4974, lng: -14.4524 },
    bloomSeason: "5月-8月",
    bloomMonths: [5, 6, 7, 8],
    flowerColors: ["白色"],
    emoji: "🦇",
    colorHex: "#F5F5F5",
    wikiImage: "https://i0.hdslb.com/bfs/archive/e846e5ab9e77b056b084501152b47e183e7b5541.jpg",
    wikiUrl: "https://zh.wikipedia.org/wiki/猴面包树",
    brief: "猴面包树是塞内加尔的国树，其花朵洁白硕大，仅在夜间绽放，由蝙蝠授粉，散发独特的酸甜气息。猴面包树在非洲文化中被视为'生命之树'，是西非稀树草原最具标志性的植物。",
    bloomGuide: "雨季5-8月夜间开放，白色花朵直径可达20厘米，花瓣蜡质，中心放射状雄蕊如白色绒球，清晨凋落。",
    viewingTips: "塞内加尔达喀尔近郊的猴面包树大道、马达加斯加穆龙达瓦猴面包树大道是观赏的绝佳地点。",
    category: "木本花卉"
  }
];

// 区域列表
const REGIONS = ["全部", "亚洲", "欧洲", "美洲", "非洲", "大洋洲"];

// 花期月份中文名
const MONTHS_CN = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"];

// 花卉类别
const CATEGORIES = ["全部类别", "木本花卉", "草本花卉", "球根花卉", "水生花卉", "附生兰花", "多肉植物", "木质藤本", "草本藤本"];

// 颜色筛选
const FLOWER_COLORS = ["全部颜色", "红色", "粉色", "白色", "黄色", "橙色", "紫色", "蓝色", "绿色"];